import React, { createContext, useContext, useState } from 'react';

export const EVENTS_DATA = [
  {
    id: 1,
    name: "Jumboo Savari",
    name_kn: "ಜಂಬೂ ಸವಾರಿ",
    name_hi: "जम्बू सवारी",
    lat: 12.3051,
    lng: 76.6551,
    description: "The grand elephant procession marking the finale of Dasara.",
    description_kn: "ದಸರಾ ಹಬ್ಬದ ಅಂತ್ಯವನ್ನು ಗುರುತಿಸುವ ಪ್ರಮುಖ ಆನೆ ಮೆರವಣಿಗೆ.",
    description_hi: "दशहरा समापन का भव्य हाथी जुलूस।",
    time: "Oct 12, 2:30 PM",
    category: "Parade",
    day: 10,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 2,
    name: "Torchlight Parade",
    name_kn: "ಪಂಜಿನ ಕವಾಯತು",
    name_hi: "टॉर्चलाइट परेड",
    lat: 12.3225,
    lng: 76.6589,
    description: "A spectacular display of lights and military drills at Bannimantap.",
    description_kn: "ಬನ್ನಿಮಂಟಪದಲ್ಲಿ ದೀಪಗಳು ಮತ್ತು ಸೇನಾ ಕವಾಯತಿನ ಅದ್ಭುತ ಪ್ರದರ್ಶನ.",
    description_hi: "बन्नीमंतप में रोशनी और सैन्य अभ्यास का शानदार प्रदर्शन।",
    time: "Oct 12, 7:00 PM",
    category: "Parade",
    day: 9,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 3,
    name: "Mysore Palace Illumination",
    name_kn: "ಮೈಸೂರು ಅರಮನೆ ದೀಪಾಲಂಕಾರ",
    name_hi: "मैसूरु पैलेस रोशनी",
    lat: 12.3052,
    lng: 76.6552,
    description: "The palace lit up with nearly 100,000 bulbs.",
    description_kn: "ಸುಮಾರು ೧ ಲಕ್ಷ ದೀಪಗಳಿಂದ ಬೆಳಗುವ ಅರಮನೆ.",
    description_hi: "लगभग एक लाख बल्बों से जगमगाता महल।",
    time: "Daily, 7:00 PM",
    category: "Sightseeing",
    day: 1,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 4,
    name: "Dasara Exhibition",
    name_kn: "ದಸರಾ ವಸ್ತುಪ್ರದರ್ಶನ",
    name_hi: "दशहरा प्रदर्शनी",
    lat: 12.3020,
    lng: 76.6600,
    description: "Shopping, food, and entertainment stalls opposite the palace.",
    description_kn: "ಅರಮನೆಯ ಎದುರು ಶಾಪಿಂಗ್, ಊಟ ಮತ್ತು ಮನರಂಜನೆ ಮಳಿಗೆಗಳು.",
    description_hi: "महल के सामने खरीदारी, भोजन और मनोरंजन स्टॉल।",
    time: "Daily, 10:00 AM - 9:00 PM",
    category: "Fair",
    day: 2,
    status: 'live',
    ageGroup: 'Family',
    ageGroup_kn: 'ಕುಟುಂಬ',
    ageGroup_hi: 'परिवार'
  },
  {
    id: 5,
    name: "Flower Show",
    name_kn: "ಫಲಪುಷ್ಪ ಪ್ರದರ್ಶನ",
    name_hi: "फूल प्रदर्शनी",
    lat: 12.307959190945715,
    lng: 76.66192000763908,
    description: "Exotic floral arrangements at Kuppanna Park.",
    description_kn: "ಕುಪ್ಪಣ್ಣ ಪಾರ್ಕ್‌ನಲ್ಲಿ ವಿಲಕ್ಷಣ ಹೂವಿನ ಅಲಂಕಾರಗಳು.",
    description_hi: "कुप्पन्ना पार्क में विदेशी पुष्प सज्जा।",
    time: "Daily, 9:00 AM - 9:00 PM",
    category: "Nature",
    day: 3,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 6,
    name: "Yuva Dasara",
    name_kn: "ಯುವ ದಸರಾ",
    name_hi: "युवा दशहरा",
    lat: 12.2552,
    lng: 76.7023,
    description: "Concerts and youth cultural programs now hosted at the expanded Uttanahalli Grounds.",
    description_kn: "ಈಗ ಉತ್ತಾನಹಳ್ಳಿ ಮೈದಾನದಲ್ಲಿ ಆಯೋಜಿಸಲ್ಪಡುವ ಸಂಗೀತ ಮತ್ತು ಯುವ ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು.",
    description_hi: "अब विस्तृत उत्तानहल्ली मैदान पर आयोजित युवा सांस्कृतिक कार्यक्रम और कॉन्सर्ट।",
    time: "Oct 6-10, 6:00 PM",
    category: "Music",
    day: 5,
    status: 'live',
    ageGroup: 'Youth',
    ageGroup_kn: 'ಯುವ',
    ageGroup_hi: 'युवा'
  },
  {
    id: 7,
    name: "Wrestling Tournament",
    name_kn: "ಕುಸ್ತಿ ಪಂದ್ಯಾವಳಿ",
    name_hi: "कुश्ती प्रतियोगिता",
    lat: 12.30530905555658,
    lng: 76.65993547827055,
    description: "Traditional Nada Kusti wrestling matches.",
    description_kn: "ಸಾಂಪ್ರದಾಯಿಕ ನಾಡ ಕುಸ್ತಿ ಪಂದ್ಯಗಳು.",
    description_hi: "परंपरागत नाडा कुश्ती मुकाबले।",
    time: "Oct 5-9, 4:00 PM",
    category: "Sports",
    day: 6,
    status: 'live',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 8,
    name: "Poets' Conference (Kavi Goshti)",
    name_kn: "ಕವಿ ಗೋಷ್ಠಿ",
    name_hi: "कवि गोष्ठी",
    lat: 12.331587841459568,
    lng: 76.61815955019668,
    description: "Gathering of renowned poets and literature lovers.",
    description_kn: "ಪ್ರಖ್ಯಾತ ಕವಿಗಳು ಮತ್ತು ಸಾಹಿತ್ಯ ಪ್ರೇಮಿಗಳ ಸಭೆ.",
    description_hi: "प्रसिद्ध कवियों और साहित्य प्रेमियों का मिलन।",
    time: "Oct 7, 10:00 AM",
    category: "Culture",
    day: 4,
    status: 'completed',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 9,
    name: "Food Mela (Ahaara Mela)",
    name_kn: "ಆಹಾರ ಮೇಳ",
    name_hi: "आहार मेला",
    lat: 12.2990,
    lng: 76.6450,
    description: "Traditional delicacies from across Karnataka.",
    description_kn: "ಕರ್ನಾಟದಾದ್ಯಂತದ ಸಾಂಪ್ರದಾಯಿಕ ಖಾದ್ಯಗಳು.",
    description_hi: "कर्नाटक भर के पारंपरिक व्यंजन।",
    time: "Daily, 11:00 AM - 10:00 PM",
    category: "Food",
    day: 7,
    status: 'live',
    ageGroup: 'Family',
    ageGroup_kn: 'ಕುಟುಂಬ',
    ageGroup_hi: 'परिवार'
  },
  {
    id: 10,
    name: "Cultural Programs at Palace",
    name_kn: "ಅರಮನೆಯಲ್ಲಿ ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು",
    name_hi: "महल में सांस्कृतिक कार्यक्रम",
    lat: 12.3051,
    lng: 76.6551,
    description: "Classical music and dance performances in front of the illuminated palace.",
    description_kn: "ದೀಪಾಲಂಕೃತ ಅರಮನೆಯ ಮುಂಭಾಗದಲ್ಲಿ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಮತ್ತು ನೃತ್ಯ ಪ್ರದರ್ಶನಗಳು.",
    description_hi: "जगमगाते महल के सामने शास्त्रीय संगीत और नृत्य प्रस्तुतियाँ।",
    time: "Daily, 6:00 PM",
    category: "Culture",
    day: 8,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 11,
    name: "Drone Light Show",
    name_kn: "ಡ್ರೋನ್ ಬೆಳಕು ಪ್ರದರ್ಶನ",
    name_hi: "ड्रोन लाइट शो",
    lat: 12.295,
    lng: 76.681,
    description: "Synchronized drones create immersive formations above Lalitha Mahal grounds.",
    description_kn: "ಲಲಿತಾ ಮಹಲ್ ಮೈದಾನದ ಮೇಲೆ ಡ್ರೋನ್‌ಗಳು ಅದ್ಭುತ ವಿನ್ಯಾಸಗಳನ್ನು ನಿರ್ಮಿಸುತ್ತವೆ.",
    description_hi: "समन्वित ड्रोन ललिता महल मैदान के ऊपर अद्भुत आकृतियां बनाते हैं।",
    time: "Oct 8-10, 8:30 PM",
    category: "Light Show",
    day: 9,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 12,
    name: "Heritage Street Performances",
    name_kn: "ಪಾರಂಪರಿಕ ರಸ್ತೆ ಪ್ರದರ್ಶನಗಳು",
    name_hi: "विरासत सड़क प्रदर्शन",
    lat: 12.3074,
    lng: 76.6529,
    description: "Traditional folk artists take over the illuminated Devaraja Market streets.",
    description_kn: "ಅಲಂಕೃತ ದೇವರಾಜ ಮಾರುಕಟ್ಟೆ ರಸ್ತೆಯಲ್ಲಿ ಪಾರಂಪರಿಕ ಜನಪದ ಕಲಾವಿದರು ಪ್ರದರ್ಶನ ನೀಡುತ್ತಾರೆ.",
    description_hi: "देवराजा मार्केट की जगमगाती गलियों में लोक कलाकार प्रस्तुतियाँ देते हैं।",
    time: "Daily, 6:00 PM - 9:00 PM",
    category: "Culture",
    day: 4,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 13,
    name: "Makkala Dasara",
    name_kn: "ಮಕ್ಕಳ ದಸರಾ",
    name_hi: "मक्कला दशहरा",
    lat: 12.3152,
    lng: 76.6308,
    description: "Interactive workshops, storytelling corners, and science demos for children.",
    description_kn: "ಮಕ್ಕಳಿಗಾಗಿ ಕಾರ್ಯಾಗಾರಗಳು, ಕಥೆ ಹೇಳುವ ಮೂಲೆಗಳು ಮತ್ತು ವಿಜ್ಞಾನ ಪ್ರದರ್ಶನಗಳು.",
    description_hi: "बच्चों के लिए कार्यशालाएँ, कहानी कोने और विज्ञान डेमो।",
    time: "Oct 4-6, 10:00 AM - 5:00 PM",
    category: "Kids",
    day: 3,
    status: 'completed',
    ageGroup: 'Kids',
    ageGroup_kn: 'ಮಕ್ಕಳು',
    ageGroup_hi: 'बच्चे'
  },
  {
    id: 14,
    name: "Raitha Dasara",
    name_kn: "ರೈತ ದಸರಾ",
    name_hi: "रैथा दशहरा",
    lat: 12.314146348041474,
    lng: 76.6469037211299,
    description: "Farmer felicitation, agri-tech demos, and organic stalls now hosted at the Scouts & Guides Grounds in Vontikoppal.",
    description_kn: "ವಂಟಿಕೊಪ್ಪಲ್ ಸ್ಕೌಟ್ಸ್ ಮತ್ತು ಗೈಡ್ಸ್ ಮೈದಾನದಲ್ಲಿ ರೈತರ ಸನ್ಮಾನ, ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ ಪ್ರದರ್ಶನ ಮತ್ತು ಸಾವಯವ ಮಳಿಗೆಗಳು.",
    description_hi: "अब वोंटि कोप्पल स्काउट्स एंड गाइड्स ग्राउंड में किसान सम्मान, एग्री-टेक डेमो व जैविक उत्पाद मेला आयोजित।",
    time: "Oct 5-7, 9:00 AM - 6:00 PM",
    category: "Agriculture",
    day: 4,
    status: 'completed',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 15,
    name: "Vintage Car Rally",
    name_kn: "ವಿಂಟೇಜ್ ಕಾರು ರ‍್ಯಾಲಿ",
    name_hi: "विंटेज कार रैली",
    lat: 12.3051,
    lng: 76.6551,
    description: "Classic cars parade from the palace to Lalitha Mahal with live commentary.",
    description_kn: "ಅರಮನೆದಿಂದ ಲಲಿತಾ ಮಹಲ್‌ವರೆಗೆ ವಿಂಟೇಜ್ ಕಾರುಗಳ ಮೆರವಣಿಗೆ ಮತ್ತು ಸಜೀವ ವಿವರಣೆ.",
    description_hi: "महल से ललिता महल तक विंटेज कारों की परेड लाइव कॉमेंट्री के साथ।",
    time: "Oct 6, 7:30 AM",
    category: "Vintage Rally",
    day: 5,
    status: 'completed',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 16,
    name: "Yoga by the Palace",
    name_kn: "ಅರಮನೆ ಬಳಿ ಯೋಗ",
    name_hi: "महल के पास योग",
    lat: 12.3046,
    lng: 76.6555,
    description: "Sunrise yoga sessions led by renowned instructors with palace backdrop.",
    description_kn: "ಪರಿಚಿತ ಶಿಕ್ಷಕರಿಂದ ಅರಮನೆ ಹಿನ್ನೆಲೆಯೊಂದಿಗೆ ಸೂರ್ಯೋದಯ ಯೋಗ ಶಿಬಿರ.",
    description_hi: "प्रसिद्ध प्रशिक्षकों के साथ महल की पृष्ठभूमि में सूर्योदय योग सत्र।",
    time: "Oct 3-9, 6:00 AM",
    category: "Wellness",
    day: 2,
    status: 'live',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 17,
    name: "Folk Dance Utsav",
    name_kn: "ಜನಪದ ನೃತ್ಯ ಉತ್ಸವ",
    name_hi: "लोक नृत्य उत्सव",
    lat: 12.310862833453944,
    lng: 76.66261409207135,
    description: "Teams from across Karnataka perform vibrant folk dances at Town Hall.",
    description_kn: "ಕರ್ನಾಟಕದ ವಿವಿಧ ತಂಡಗಳು ಟೌನ್ ಹಾಲ್‌ನಲ್ಲಿ ಚೆಲುವಾದ ಜನಪದ ನೃತ್ಯ ಪ್ರದರ್ಶನ ನೀಡುತ್ತವೆ.",
    description_hi: "कर्नाटक भर की टीमें टाउन हॉल में रंगीन लोक नृत्य प्रस्तुत करती हैं।",
    time: "Oct 7-9, 5:00 PM - 8:00 PM",
    category: "Dance",
    day: 6,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 18,
    name: "Adventure Sports Zone",
    name_kn: "ಸಾಹಸ ಕ್ರೀಡೆ ವಲಯ",
    name_hi: "एडवेंचर स्पोर्ट्स ज़ोन",
    lat: 12.276707637748268,
    lng: 76.67075573202106,
    description: "Ziplining, wall climbing, and obstacle courses at Chamundi Vihar Stadium.",
    description_kn: "ಚಾಮುಂಡಿ ವಿಹಾರ ಕ್ರೀಡಾಂಗಣದಲ್ಲಿ ಜಿಪ್‌ಲೈನ್, ಗೋಡೆ ಏರಿಕೆ ಮತ್ತು ಅಡೆತಡೆ ಆಟಗಳು.",
    description_hi: "चामुंडी विहार स्टेडियम में ज़िपलाइन, वॉल क्लाइम्ब और बाधा पाठ्यक्रम।",
    time: "Oct 5-10, 10:00 AM - 7:00 PM",
    category: "Adventure",
    day: 7,
    status: 'live',
    ageGroup: 'Youth',
    ageGroup_kn: 'ಯುವ',
    ageGroup_hi: 'युवा'
  }
];

const EVENT_VENUE_MAP = {
  1: {
    venue: 'Mysuru Palace to Bannimantap Grounds',
    nearbyStops: ['palace bus stop', 'bannimantap depot out gate']
  },
  2: {
    venue: 'Torch Light Parade Grounds, Bannimantap',
    nearbyStops: ['bannimantap depot out gate', 'city bus stand']
  },
  3: {
    venue: 'Mysuru Palace Forecourt',
    nearbyStops: ['palace bus stop', 'hardinge circle']
  },
  4: {
    venue: 'Dasara Exhibition Grounds (Doddakere Maidan)',
    nearbyStops: ['mysore rural bus stand', 'palace bus stop']
  },
  5: {
    venue: 'Kuppanna Park',
    nearbyStops: ['five light circle', 'nanju malige', 'hardinge circle']
  },
  6: {
    venue: 'Uttanahalli Grounds (near Chamundi foothills)',
    nearbyStops: ['chamundi hill', 'mysore zoo', 'chamundipuram']
  },
  7: {
    venue: 'Exhibition Authority Premises',
    nearbyStops: ['palace bus stop', 'mysore rural bus stand']
  },
  8: {
    venue: 'Kannada Sahitya Parishat, Chamaraja Double Road',
    nearbyStops: ['dasappa circle', 'vani vilas water works', 'city bus stand']
  },
  9: {
    venue: "Maharaja's College Grounds",
    nearbyStops: ['maharani college', 'railway station']
  },
  10: {
    venue: 'Mysuru Palace Cultural Stage',
    nearbyStops: ['palace bus stop', 'hardinge circle']
  },
  11: {
    venue: 'Torch Light Parade Grounds (Bannimantap)',
    nearbyStops: ['bannimantap depot out gate', 'city bus stand']
  },
  12: {
    venue: 'Sayyaji Rao Road & Devaraja Market Precinct',
    nearbyStops: ['dodda gadiyara', 'city bus stand', 'dasappa circle']
  },
  14: {
    venue: 'Scouts & Guides Grounds, Vontikoppal',
    nearbyStops: ['vonti koppal temple', 'maharani college', 'railway station']
  },
  15: {
    venue: 'Mysuru Palace Forecourt',
    nearbyStops: ['palace bus stop', 'hardinge circle']
  },
  16: {
    venue: 'Eastern Lawns, Mysuru Palace',
    nearbyStops: ['palace bus stop', 'hardinge circle']
  },
  17: {
    venue: 'Town Hall Steps & Ramaswamy Circle',
    nearbyStops: ['ramaswamy circle', 'ashoka circle', 'rto']
  },
  18: {
    venue: 'Chamundi Vihar Stadium & Foothills',
    nearbyStops: ['mysore zoo', 'chamundipuram', 'chamundi hill']
  }
};

EVENTS_DATA.forEach((event) => {
  if (EVENT_VENUE_MAP[event.id]) {
    Object.assign(event, EVENT_VENUE_MAP[event.id]);
  }
});

export const ROAD_CLOSURES = [
  {
    id: 'closure-palace-road',
    name: 'Palace Road Barricade',
    name_kn: 'ಅರಮನೆ ರಸ್ತೆ ಅಡ್ಡಿ',
    lat: 12.3058,
    lng: 76.6558,
    description: 'Access closed for parade rehearsal from 1 PM - 8 PM.',
    description_kn: 'ಮೆರವಣಿಗೆ ಅಭ್ಯಾಸದ ಕಾರಣ ಮಧ್ಯಾಹ್ನ ೧ ರಿಂದ ರಾತ್ರಿ ೮ರವರೆಗೆ ಪ್ರವೇಶ ಮುಚ್ಚಲಾಗಿದೆ.',
    days: [9, 10],
    radius: 220
  },
  {
    id: 'closure-torchlight-main-gate',
    name: 'Torchlight Parade Grounds Main Gate Diversion',
    name_kn: 'ಟಾರ್ಚ್‌ಲೈಟ್ ಪೆರೇಡ್ ಮುಖ್ಯ ಗೇಟ್ ಮಾರ್ಗ ಬದಲಾವಣೆ',
    lat: 12.3420,
    lng: 76.6530,
    description: 'Road diversion near Torchlight Parade Grounds main gate for finale setup from 2 PM - 11 PM.',
    description_kn: 'ಟಾರ್ಚ್‌ಲೈಟ್ ಪೆರೇಡ್ ಮುಖ್ಯ ಗೇಟ್ ಬಳಿ ಅಂತಿಮ ಸಿದ್ಧತೆಗಾಗಿ ಮಧ್ಯಾಹ್ನ ೨ ರಿಂದ ರಾತ್ರಿ ೧೧ರವರೆಗೆ ಮಾರ್ಗ ಬದಲಾವಣೆ.',
    days: [10],
    radius: 180
  },
  {
    id: 'closure-doddakere',
    name: 'Doddakere Maidan Parking Restriction',
    name_kn: 'ದೊಡ್ಡಕೆರೆ ಮೈದಾನ ವಾಹನ ನಿಲುಗಡೆ ನಿರ್ಬಂಧ',
    lat: 12.3036,
    lng: 76.6579,
    description: 'Only shuttle buses allowed between 9 AM - 11 PM.',
    description_kn: 'ಬೆಳಿಗ್ಗೆ ೯ರಿಂದ ರಾತ್ರಿ ೧೧ರವರೆಗೆ ಶಟಲ್ ಬಸ್ಸುಗಳಿಗೆ ಮಾತ್ರ ಅನುಮತಿ.',
    days: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    radius: 160
  },
  {
    id: 'closure-jamboo-route',
    name: 'Jamboo Savari Procession Route',
    name_kn: 'ಜಂಬೂ ಸವಾರಿ ಮೆರವಣಿಗೆ ಮಾರ್ಗ',
    lat: 12.3198,
    lng: 76.6607,
    description: 'Entire 5 km corridor from Mysuru Palace (Balarama Gate) to Bannimantap Grounds closed for vehicles from 8 AM - 8 PM on the grand finale day.',
    description_kn: 'ಅಂತಿಮ ದಿನ ಬೆಳಿಗ್ಗೆ ೮ ರಿಂದ ರಾತ್ರಿ ೮ರವರೆಗೆ ಮೈಸೂರು ಅರಮನೆ (ಬಾಲರಾಮ ದಿಂದ)ದಿಂದ ಬನ್ನಿಮಂಟಪ ಮೈದಾನವರೆಗೆ ೫ ಕಿಮೀ ಮಾರ್ಗವು ಎಲ್ಲಾ ವಾಹನಗಳಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಮುಚ್ಚಲ್ಪಟ್ಟಿದೆ.',
    days: [10],
    radius: 120,
    pathBuffer: 250,
    path: [
      { lat: 12.305163, lng: 76.6551749 },
      { lat: 12.30568, lng: 76.65594 },
      { lat: 12.30664, lng: 76.6569 },
      { lat: 12.30775, lng: 76.65793 },
      { lat: 12.30894, lng: 76.65848 },
      { lat: 12.31012, lng: 76.65841 },
      { lat: 12.31193, lng: 76.65766 },
      { lat: 12.31375, lng: 76.65705 },
      { lat: 12.31568, lng: 76.65647 },
      { lat: 12.31752, lng: 76.65602 },
      { lat: 12.31913, lng: 76.65566 },
      { lat: 12.32074, lng: 76.65545 },
      { lat: 12.32247, lng: 76.65531 },
      { lat: 12.32428, lng: 76.6552 },
      { lat: 12.32606, lng: 76.65512 },
      { lat: 12.32782, lng: 76.65504 },
      { lat: 12.32959, lng: 76.655 },
      { lat: 12.33147, lng: 76.65499 },
      { lat: 12.33328, lng: 76.65499 },
      { lat: 12.3340167, lng: 76.6549883 }
    ]
  }
];

const CURRENT_YEAR = new Date().getFullYear();
const DIGIT_MAPS = {
  kn: { '0': '೦', '1': '೧', '2': '೨', '3': '೩', '4': '೪', '5': '೫', '6': '೬', '7': '೭', '8': '೮', '9': '೯' },
  hi: { '0': '०', '1': '१', '2': '२', '3': '३', '4': '४', '5': '५', '6': '६', '7': '७', '8': '८', '9': '९' }
};

const toLocalizedDigits = (value, locale) => {
  const map = DIGIT_MAPS[locale];
  if (!map) {
    return String(value);
  }
  return String(value)
    .split('')
    .map((char) => map[char] || char)
    .join('');
};

const EN_FESTIVAL_DATES = `Navaratri • 1 – 10 Oct ${CURRENT_YEAR}`;
const KN_FESTIVAL_DATES = `ನವ ರಾತ್ರಿ • ಅಕ್ಟೋಬರ್ ${toLocalizedDigits(1, 'kn')} – ${toLocalizedDigits(10, 'kn')}, ${toLocalizedDigits(CURRENT_YEAR, 'kn')}`;
const HI_FESTIVAL_DATES = `नवरात्रि • ${toLocalizedDigits(1, 'hi')} – ${toLocalizedDigits(10, 'hi')} अक्तूबर ${toLocalizedDigits(CURRENT_YEAR, 'hi')}`;

const EN_FOOTER_COPY = `© ${CURRENT_YEAR} Dasara Mitra. Celebrating the spirit of Mysore.`;
const KN_FOOTER_COPY = `© ${toLocalizedDigits(CURRENT_YEAR, 'kn')} ದಸರಾ ಮಿತ್ರ. ಮೈಸೂರಿನ ಸಂಭ್ರಮವನ್ನು ಆಚರಿಸೋಣ.`;
const HI_FOOTER_COPY = `© ${toLocalizedDigits(CURRENT_YEAR, 'hi')} दसरा मित्र। मैसूर की परंपरा का उत्सव।`;

export const TRANSLATIONS = {
  en: {
    title: "Dasara Mitra",
    heroTitle: "Welcome to Mysore Dasara",
    heroSubtitle: "Your Festival Companion – Navigate events, transport, and memories effortlessly.",
    ctaEvents: "Find Nearest Events",
    ctaGallery: "Explore Gallery",
    eventsTitle: "Festival Events Map",
    eventsHeroDescription: "Discover marquee Mysuru Dasara highlights, pin their exact locations, and stay informed on start times before you step out.",
    transportTitle: "Transport Route Planner",
    transportHeroDescription: "Plan your way between venues with quick travel estimates across buses, taxis, and autos tuned for the festive rush.",
    galleryTitle: "Photo Gallery",
    galleryHeroDescription: "Relive golden Dasara memories through curated visuals from palace lights to Chamundi hilltop vistas.",
    galleryFallbackTitle: "Festival Highlights",
    galleryFallbackBlurb: "Handpicked palace nights, processions, and cultural vibes.",
    galleryLoadingMessage: "Loading festival memories from Cloudinary...",
    galleryCloudinaryEmpty: "Cloudinary returned no images for the configured tags. Showing the default gallery.",
    galleryCloudinaryError: "We couldn't load the Cloudinary gallery right now. Showing the default photos instead.",
    galleryNoImages: "No images have been uploaded for {{section}} yet.",
    gallerySectionPalaceTitle: "Mysuru Palace",
    gallerySectionPalaceBlurb: "Illuminations, rituals, and royal courtside views.",
    gallerySectionFlowerTitle: "Flower Show",
    gallerySectionFlowerBlurb: "Kuppanna Park floral sculptures and installations.",
    gallerySectionProcessionTitle: "Jumboo Savari Procession",
    gallerySectionProcessionBlurb: "Grand finale moments along Sayyaji Rao Road.",
    gallerySectionLightingsTitle: "City Lightings",
    gallerySectionLightingsBlurb: "Heritage streets dressed in shimmering lights.",
    gallerySectionCulturalTitle: "Cultural Activities",
    gallerySectionCulturalBlurb: "Music, dance, and theatre from Yuva Dasara stages.",
    gallerySectionYuvaTitle: "Yuva Dasara",
    gallerySectionYuvaBlurb: "Youth concerts and late-night gigs across Mysuru.",
    gallerySectionChamundiTitle: "Chamundi Temple",
    gallerySectionChamundiBlurb: "Spiritual calm atop Chamundi Hills.",
    gallerySectionExhibitionTitle: "Dasara Exhibition",
    gallerySectionExhibitionBlurb: "Shops, rides, and nostalgia at Doddakere Maidan.",
    gallerySectionTableauTitle: "Procession Tableaux",
    gallerySectionTableauBlurb: "Artistic floats depicting Mysuru heritage during Jumboo Savari.",
    gallerySectionWrestlingTitle: "Wrestling Tournament",
    gallerySectionWrestlingBlurb: "Nada Kusti akhada bouts and champion grapplers.",
    gallerySectionDroneTitle: "Drone Light Show",
    gallerySectionDroneBlurb: "Synchronised aerial stories lighting up Lalitha Mahal skies.",
    gallerySectionVintageTitle: "Vintage Car Rally",
    gallerySectionVintageBlurb: "Classic beauties cruising from Mysuru Palace to Lalitha Mahal lawns.",
    footerEventsCardDescription: "Pin every Mysuru celebration and dive into the royal schedule.",
    footerTransportCardDescription: "Plan diversions, shuttles, and festival commutes with confidence.",
    footerGalleryCardDescription: "Relive palace illuminations and cultural memories on demand.",
    footerExploreCta: "Explore",
    home: "Home",
    events: "Events",
    transport: "Transport",
    gallery: "Gallery",
    findRoute: "Find Route",
    fromEvent: "From Event",
    toEvent: "To Event",
    calculating: "Calculating...",
    routeDetails: "Route Details",
    footerText: EN_FOOTER_COPY,
    footerAboutTitle: "About Dasara Mitra",
    footerAboutDescription: "Your bilingual festival navigator for routes, events, and on-ground essentials during Mysuru Dasara.",
    footerDiscoverTitle: "Discover Dasara",
    footerVisitTitle: "Plan your visit",
    footerContactTitle: "Festival helpdesk",
    footerContactPhoneLabel: "Helpline",
    footerContactPhoneValue: "+91 78931XXXXX",
    footerContactEmailLabel: "Email",
    footerContactEmailValue: "artappreciating@gmail.com",
    footerContactHoursLabel: "Timings",
    footerContactHoursValue: "Daily 9 AM – 10 PM IST",
    footerContactOfficeLabel: "Command center",
    footerContactOfficeValue: "Dasara Exhibition Grounds, Mysuru",
    footerConnectTitle: "Stay in touch",
    footerAddress: "Mysuru, Karnataka, India",
    footerDisclaimer: "Community-built companion. Information verified with Mysuru Dasara authorities.",
    footerFestivalDates: EN_FESTIVAL_DATES,
    footerPlanTip: "Arrive by 4 PM to secure vantage points for the grand Jamboo Savari procession.",
    footerDailyFlowTitle: "Daily Festival Flow",
    footerDailyFlowDescription: "Stay ahead of the day-wise highlights and never miss a spectacle.",
    footerSocialTitle: "Follow the celebrations",
    footerSocialInstagram: "Instagram",
    footerSocialYoutube: "YouTube",
    footerSocialFacebook: "Facebook",
    footerSocialX: "X (Twitter)",
    footerNewsletterTitle: "Festival bulletin",
    footerNewsletterDescription: "Get daily highlights, road updates, and exclusive cultural insights in your inbox.",
    footerNewsletterPlaceholder: "Enter your email",
    footerNewsletterCta: "Keep me updated",
    footerNewsletterDisclaimer: "No spam. Unsubscribe anytime. Updates shared during festival week.",
    contactFormTitle: "Write to the helpdesk",
    contactFormDescription: "Drop your query and we'll route it to the Dasara control room.",
    contactFormNameLabel: "Full name",
    contactFormEmailLabel: "Email address",
    contactFormMessageLabel: "Message",
    contactFormSubmitLabel: "Send message",
    contactFormSendingLabel: "Sending...",
    contactFormSuccess: "Thanks! Your message has been shared with the helpdesk.",
    contactFormError: "Unable to send your message right now. Please try again shortly.",
    contactFormSettingsError: "Email service is not configured. Add the EmailJS environment variables to enable outgoing mail.",
    contactFormValidationError: "Please add your name, a valid email, and a short message before sending.",
    nearest: "Nearest to you",
    chatTitle: "Dasara Helper",
    chatPlaceholder: "Ask about events, routes, or history...",
    send: "Send",
    loading: "Loading...",
    error: "Something went wrong.",
    voiceAssistTitle: "Voice Navigator",
    voiceAssistHint: "Tap the mic and ask about routes, events, or travel tips.",
    voiceAssistListening: "Listening...",
    voiceAssistProcessing: "Fetching answer...",
    voiceAssistResponded: "Answer ready",
    voiceAssistError: "Mic issue",
    voiceAssistReady: "Tap to ask",
    voiceAssistUnsupported: "Voice assistance is not supported in this browser.",
    voiceAssistTranscriptLabel: "You asked",
    voiceAssistPromptExample: "Ask: 'Where does Jamboo Savari start?'",
    voiceAssistResponseLabel: "Assistant reply",
    voiceAssistErrorDetail: "Unable to capture audio",
    voiceAssistStopListening: "Stop",
    voiceAssistTapToSpeak: "Tap to speak",
    voiceAssistStopAudio: "Stop audio",
    voiceAssistReplayAudio: "Replay audio",
    enableLocation: "Enable location to find events near you!",
    locationDenied: "Location access denied. Showing all events.",
    category: "Category",
    time: "Time",
    directions: "Get Directions",
    distance: "Distance",
    duration: "Duration",
    routeNeedLocation: "Enable location to get directions.",
    routeFetching: "Fetching the best route...",
    routeUnavailable: "Route unavailable right now. Please try again in a moment.",
    routeReady: "Walking route ready",
    clearRoute: "Clear Route",
    busSupportTitle: "Nearby KSRTC city buses",
    busSupportSubtitle: "Use these stops closest to the venue.",
    busLoadingStatus: "Mapping stops...",
    busErrorStatus: "Unable to load the city bus network right now.",
    busListLabel: "Buses",
    busNoStops: "No mapped city stops yet.",
    eventVenueLabel: "Venue",
    searchPlaceholder: "Search events or categories...",
    clearSearch: "Clear",
    dayFilterLabel: "Filter by day",
    allDays: "All days",
    dayLabel: "Day",
    categoryFilterLabel: "Filter by category",
    allCategories: "All categories",
    ageFilterLabel: "Age category",
    allAgeGroups: "All age groups",
    statusLabel: "Status",
    statusLive: "Live",
    statusUpcoming: "Upcoming",
    statusCompleted: "Completed",
    routeInstructionsTitle: "Turn-by-turn directions",
    noInstructions: "Detailed steps are unavailable for this route.",
    routeRestrictionsTitle: "Route advisories",
    noRestrictions: "No restrictions along this route.",
    activeOnDays: "Active on days",
    restrictionRadius: "Restricted radius",
    metersUnit: "m",
    kilometersUnit: "km",
    secondsUnitShort: "sec",
    minutesUnitShort: "min",
    jambooStartLabel: "Mysuru Palace – Balarama Gate",
    jambooEndLabel: "Bannimantap Grounds",
    jambooRouteLabel: "Grand Procession Corridor",
    processionRouteTitle: "Jamboo Savari Procession",
    processionRouteSubtitle: "Mysore Palace to Bannimantap Grounds",
    processionFocusCta: "Focus Route",
    processionStopsHeading: "Route Landmarks",
    processionStartingPoint: "Starting Point",
    processionEndingPoint: "Ending Point",
    processionCardMapView: "Map view",
    processionCardShow: "Show card",
    showClosures: "Show road blockages",
    hideClosures: "Hide road blockages",
    closuresTitle: "Road blockages",
    noEvents: "No events available.",
    noEventsForDay: "No events scheduled for Day",
    noSearchResults: "No matches for",
    searchHint: "Try a different event name or clear the filters to explore everything.",
    noFilterResults: "No events match the selected filters."
  },
  kn: {
    title: "ದಸರಾ ಮಿತ್ರ",
    heroTitle: "ಮೈಸೂರು ದಸರಾಗೆ ಸ್ವಾಗತ",
    heroSubtitle: "ನಿಮ್ಮ ಹಬ್ಬದ ಸಂಗಾತಿ - ಕಾರ್ಯಕ್ರಮಗಳು, ಸಾರಿಗೆ ಮತ್ತು ನೆನಪುಗಳನ್ನು ಸುಲಭವಾಗಿ ಅನ್ವೇಷಿಸಿ.",
    ctaEvents: "ಹತ್ತಿರದ ಕಾರ್ಯಕ್ರಮಗಳು",
    ctaGallery: "ಗ್ಯಾಲರಿ ವೀಕ್ಷಿಸಿ",
    eventsTitle: "ದಸರಾ ಕಾರ್ಯಕ್ರಮಗಳ ನಕ್ಷೆ",
    eventsHeroDescription: "ಮೈಸೂರಿನ ಪ್ರಮುಖ ದಸರಾ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಗುರುತಿಸಿ, ಅವುಗಳ ನಿಖರ ಸ್ಥಳಗಳನ್ನು ಪಿನ್ ಮಾಡಿ ಮತ್ತು ಸಮಯಗಳ ಬಗ್ಗೆ ಮುಂಚಿತ ಮಾಹಿತಿ ಪಡೆಯಿರಿ.",
    transportTitle: "ಸಾರಿಗೆ ಮಾರ್ಗಗಳು",
    transportHeroDescription: "ಹಬ್ಬದ ಗದ್ದಲಕ್ಕೆ ಹೊಂದುವಂತೆ ಬಸ್ಸು, ಟ್ಯಾಕ್ಸಿ ಮತ್ತು ಆಟೋಗಳ ಅಂದಾಜುಗಳನ್ನು ಪಡೆದು ಸ್ಥಳಗಳಿಂದ ಸ್ಥಳಗಳಿಗೆ ಪ್ರಯಾಣವನ್ನು ಯೋಜಿಸಿ.",
    galleryTitle: "ಛಾಯಾಚಿತ್ರ ಗ್ಯಾಲರಿ",
    galleryHeroDescription: "ಅರಮನೆ ಬೆಳಕುಗಳಿಂದ ಚಾಮುಂಡಿ ಬೆಟ್ಟದ ದೃಶ್ಯಗಳಿಗೆ ಹೃದಯಸ್ಪರ್ಶಿ ದಸರಾ ಕ್ಷಣಗಳನ್ನು ಮರು ಅನುಭವಿಸಿ.",
    galleryFallbackTitle: "ಹಬ್ಬದ ಮುಖ್ಯಾಂಶಗಳು",
    galleryFallbackBlurb: "ಅರಮನೆ ರಾತ್ರಿ, ಮೆರವಣಿಗೆ ಮತ್ತು ಸಂಸ್ಕೃತಿಯ ಹೃದಯಸ್ಪರ್ಶಿ ಕ್ಷಣಗಳು.",
    galleryLoadingMessage: "ಕ್ಲೌಡಿನರಿ ಯಿಂದ ಹಬ್ಬದ ಚಿತ್ರಗಳನ್ನು ತರಲಾಗುತ್ತಿದೆ...",
    galleryCloudinaryEmpty: "ನಿಗದಿಪಡಿಸಿದ ಟ್ಯಾಗ್‌ಗಳಿಗೆ ಕ್ಲೌಡಿನರಿ ಚಿತ್ರಗಳನ್ನು ನೀಡಲಿಲ್ಲ. ಪೂರ್ವನಿಗದಿತ ಗ್ಯಾಲರಿಯನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    galleryCloudinaryError: "ಈ ಕ್ಷಣ ಕ್ಲೌಡಿನರಿ ಗ್ಯಾಲರಿಯನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ. ಮೂಲಸ್ಥಿತಿ ಚಿತ್ರಗಳನ್ನು ತೋರಲಾಗುತ್ತಿದೆ.",
    galleryNoImages: "{{section}} ಗಾಗಿ ಇನ್ನೂ ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿಲ್ಲ.",
    gallerySectionPalaceTitle: "ಮೈಸೂರು ಅರಮನೆ",
    gallerySectionPalaceBlurb: "ದೀಪಾಲಂಕಾರ, ರಾಜವಿಧಿಗಳು ಮತ್ತು ಅರಮನೆ ದೃಶ್ಯಗಳು.",
    gallerySectionFlowerTitle: "ಹೂವಿನ ಪ್ರದರ್ಶನ",
    gallerySectionFlowerBlurb: "ಕುಪ್ಪಣ್ಣ ಪಾರ್ಕ್‌ನ ಹೂ ಶಿಲ್ಪಗಳು ಮತ್ತು ಕಲಾತ್ಮಕ ಸಿದ್ಧತೆ.",
    gallerySectionProcessionTitle: "ಜಂಬೂ ಸವಾರಿ ಮೆರವಣಿಗೆ",
    gallerySectionProcessionBlurb: "ಸಯ್ಯಜಿ ರಾವ್ ರಸ್ತೆಯಲ್ಲಿ ನಡೆಯುವ ಅಂತಿಮ ದಿನದ ಸಂಭ್ರಮ.",
    gallerySectionLightingsTitle: "ನಗರ ದೀಪಾಲಂಕಾರ",
    gallerySectionLightingsBlurb: "ಪರಂಪರೆಯ ಬೀದಿಗಳಲ್ಲಿ ಹೊಳೆಯುವ ದೀಪ ಸಜ್ಜೆ.",
    gallerySectionCulturalTitle: "ಸಾಂಸ್ಕೃತಿಕ ಚಟುವಟಿಕೆಗಳು",
    gallerySectionCulturalBlurb: "ಯುವ ದಸರಾ ವೇದಿಕೆಯಲ್ಲಿ ಸಂಗೀತ, ನೃತ್ಯ ಮತ್ತು ನಾಟಕಗಳು.",
    gallerySectionYuvaTitle: "ಯುವ ದಸರಾ",
    gallerySectionYuvaBlurb: "ನಗರದ ವಿವಿಧ ವೇದಿಕೆಗಳಲ್ಲಿ ಯುವ ಸಂಗೀತ ಮತ್ತು ರಾತ್ರಿ ಕಾರ್ಯಕ್ರಮಗಳು.",
    gallerySectionChamundiTitle: "ಚಾಮುಂಡಿ ದೇವಾಲಯ",
    gallerySectionChamundiBlurb: "ಚಾಮುಂಡಿ ಬೆಟ್ಟದ ಆರಾಧನೆಯ ಶಾಂತ ವಾತಾವರಣ.",
    gallerySectionExhibitionTitle: "ದಸರಾ ಪ್ರದರ್ಶನ",
    gallerySectionExhibitionBlurb: "ದೊಡ್ಡಕೆರೆ ಮೈದಾನದಲ್ಲಿನ ಅಂಗಡಿಗಳು, ರೈಡ್‌ಗಳು ಮತ್ತು ನೆನಪುಗಳು.",
    gallerySectionTableauTitle: "ಮೆರವಣಿಗೆ ತಾಳೆಗಳು",
    gallerySectionTableauBlurb: "ಜಂಬೂ ಸವಾರಿಯಲ್ಲಿ ಮೈಸೂರಿನ ಪರಂಪರೆಯನ್ನು ತೋರಿಸುವ ಕಲಾತ್ಮಕ ತಾಳೆಗಳು.",
    gallerySectionWrestlingTitle: "ಕುಸ್ತಿ ಸ್ಪರ್ಧೆ",
    gallerySectionWrestlingBlurb: "ನಾಡ ಕುಸ್ತಿ ಅಖಾಡದಲ್ಲಿ ನಡೆಯುವ ಪೈಪೋಟಿ ಕಾಳಗಗಳು.",
    gallerySectionDroneTitle: "ಡ್ರೋನ್ ಬೆಳಕು ಪ್ರದರ್ಶನ",
    gallerySectionDroneBlurb: "ಲಲಿತಾ ಮಹಲ್ ಆಕಾಶದಲ್ಲಿ ಸಮನ್ವಯಿತ ಬೆಳಕು ಕಥೆಗಳು.",
    gallerySectionVintageTitle: "ವಿಂಟೇಜ್ ಕಾರು ರ‍್ಯಾಲಿ",
    gallerySectionVintageBlurb: "ಮೈಸೂರು ಅರಮನೆದಿಂದ ಲಲಿತಾ ಮಹಲ್ ತನಕ ಚಲಿಸುವ ವಿಂಟೇಜ್ ಕಾರು ಮೆರವಣಿಗೆ.",
    footerEventsCardDescription: "ನಗರದಲ್ಲಿ ನಡೆಯುವ ದಸರಾ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಸುಲಭವಾಗಿ ಪತ್ತೆ ಹಚ್ಚಿ.",
    footerTransportCardDescription: "ಮೆರವಣಿಗೆ ದಾರಿಗಳ ಬದಲಾವಣೆ ಮತ್ತು ಶಟಲ್ ಆಯ್ಕೆಗಳನ್ನು ಯೋಜಿಸಿ.",
    footerGalleryCardDescription: "ಅರಮನೆ ಬೆಳಕು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಕ್ಷಣಗಳನ್ನು ಮರು ಅನುಭವಿಸಿ.",
    footerExploreCta: "ಇನ್ನಷ್ಟು ಅನ್ವೇಷಿಸಿ",
    home: "ಮುಖಪುಟ",
    events: "ಕಾರ್ಯಕ್ರಮಗಳು",
    transport: "ಸಾರಿಗೆ",
    gallery: "ಗ್ಯಾಲರಿ",
    findRoute: "ಮಾರ್ಗ ಹುಡುಕಿ",
    fromEvent: "ಇಲ್ಲಿಂದ",
    toEvent: "ಇಲ್ಲಿಗೆ",
    calculating: "ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತಿದೆ...",
    routeDetails: "ಮಾರ್ಗದ ವಿವರಗಳು",
    footerText: KN_FOOTER_COPY,
    footerAboutTitle: "ದಸರಾ ಮಿತ್ರ ಬಗ್ಗೆ",
    footerAboutDescription: "ಮೈಸೂರು ದಸರಾದ ಸಮಯದಲ್ಲಿ ಮಾರ್ಗಗಳು, ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ಅಗತ್ಯ ಮಾಹಿತಿಗಾಗಿ ನಿಮ್ಮ ದ್ವಿಭಾಷಾ ಮಾರ್ಗದರ್ಶಿ.",
    footerDiscoverTitle: "ದಸರಾ ಅನ್ವೇಷಿಸಿ",
    footerVisitTitle: "ನಿಮ್ಮ ಪ್ರವಾಸ ಯೋಜಿಸಿ",
    footerContactTitle: "ಹಬ್ಬದ ಸಹಾಯ ಕೇಂದ್ರ",
    footerContactPhoneLabel: "ಸಹಾಯವಾಣಿ",
    footerContactPhoneValue: "+91 78931XXXXX",
    footerContactEmailLabel: "ಇಮೇಲ್",
    footerContactEmailValue: "artappreciating@gmail.com",
    footerContactHoursLabel: "ಸೇವಾ ಸಮಯ",
    footerContactHoursValue: "ಪ್ರತಿದಿನ ಬೆಳಿಗ್ಗೆ ೯ – ರಾತ್ರಿ ೧೦ (IST)",
    footerContactOfficeLabel: "ನಿಯಂತ್ರಣ ಕೇಂದ್ರ",
    footerContactOfficeValue: "ದಸರಾ ಪ್ರದರ್ಶನ ಮೈದಾನ, ಮೈಸೂರು",
    footerConnectTitle: "ಸಂಪರ್ಕಿಸಿ",
    footerAddress: "ಮೈಸೂರು, ಕರ್ನಾಟಕ, ಭಾರತ",
    footerDisclaimer: "ಸಮುದಾಯ ನಿರ್ಮಿತ ಮಾರ್ಗದರ್ಶಿ. ಮೈಸೂರು ದಸರಾ ಆಡಳಿತದಿಂದ ಪರಿಶೀಲಿತ ಮಾಹಿತಿ.",
    footerFestivalDates: KN_FESTIVAL_DATES,
    footerPlanTip: "ಜಂಬೂ ಸವಾರಿ ಭವ್ಯ ಮೆರವಣಿಗೆ ವೀಕ್ಷಿಸಲು ಸಂಜೆ ೪ಕ್ಕೆ ಮುನ್ನ ಸ್ಥಳ ತಲುಪಿ.",
    footerDailyFlowTitle: "ದಿನವಾರ ಹಬ್ಬದ ಹೊಳೆ",
    footerDailyFlowDescription: "ಪ್ರತಿ ದಿನದ ಸಂಭವಗಳನ್ನು ತಿಳಿದು ವಿಶೇಷ ಕ್ಷಣಗಳನ್ನು ತಪ್ಪಿಸಿಕೊಳ್ಳಬೇಡಿ.",
    footerSocialTitle: "ಹಬ್ಬದ ಕ್ಷಣಗಳನ್ನು ಅನುಸರಿಸಿ",
    footerSocialInstagram: "Instagram",
    footerSocialYoutube: "YouTube",
    footerSocialFacebook: "Facebook",
    footerSocialX: "X (Twitter)",
    footerNewsletterTitle: "ಹಬ್ಬದ ಸುದ್ದಿ ಪತ್ರಿಕೆ",
    footerNewsletterDescription: "ಪ್ರತಿ ದಿನದ ಮುಖ್ಯಾಂಶಗಳು, ಮಾರ್ಗ ಬದಲಾವಣೆಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ವಿವರಗಳನ್ನು ನೇರವಾಗಿ ಪಡೆಯಿರಿ.",
    footerNewsletterPlaceholder: "ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    footerNewsletterCta: "ನನ್ನನ್ನು ತಿಳಿಸಿ",
    footerNewsletterDisclaimer: "Spam ಇಲ್ಲ. ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಬೇರ್ಪಡಿಸಬಹುದು. ಹಬ್ಬದ ಅವಧಿಯಲ್ಲಿ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಹಂಚಲಾಗುತ್ತದೆ.",
    contactFormTitle: "ಸಹಾಯ ಕೇಂದ್ರಕ್ಕೆ ಬರೆಯಿರಿ",
    contactFormDescription: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಹಂಚಿ, ನಾವು ಅದನ್ನು ದಸರಾ ನಿಯಂತ್ರಣ ಕೋಣೆಗೆ ಸಾಗಿಸುತ್ತೇವೆ.",
    contactFormNameLabel: "ಪೂರ್ಣ ಹೆಸರು",
    contactFormEmailLabel: "ಇಮೇಲ್ ವಿಳಾಸ",
    contactFormMessageLabel: "ಸಂದೇಶ",
    contactFormSubmitLabel: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    contactFormSendingLabel: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
    contactFormSuccess: "ಧನ್ಯವಾದಗಳು! ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಸಹಾಯ ಕೇಂದ್ರಕ್ಕೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
    contactFormError: "ಈ ಕ್ಷಣ ಸಂದೇಶ ಕಳುಹಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    contactFormSettingsError: "ಇಮೇಲ್ ಸೇವೆ ಸಕ್ರಿಯಗೊಂಡಿಲ್ಲ. EmailJS ಪರಿಸರ ಮೌಲ್ಯಗಳನ್ನು ಸೇರಿಸಿ.",
    contactFormValidationError: "ಕಳುಹಿಸುವ ಮೊದಲು ನಿಮ್ಮ ಹೆಸರು, ಮಾನ್ಯ ಇಮೇಲ್ ಮತ್ತು ಸಂದೇಶವನ್ನು ನಮೂದಿಸಿ.",
    nearest: "ನಿಮ್ಮ ಹತ್ತಿರ",
    chatTitle: "ದಸರಾ ಸಹಾಯಕ",
    chatPlaceholder: "ಕಾರ್ಯಕ್ರಮಗಳು, ಮಾರ್ಗಗಳು ಅಥವಾ ಇತಿಹಾಸದ ಬಗ್ಗೆ ಕೇಳಿ...",
    send: "ಕಳುಹಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error: "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
    voiceAssistTitle: "ಧ್ವನಿ ಸಹಾಯಕ",
    voiceAssistHint: "ಮೈಕ್ ಒತ್ತಿ ಮಾರ್ಗಗಳು ಅಥವಾ ಕಾರ್ಯಕ್ರಮಗಳ ಬಗ್ಗೆ ಕೇಳಿ.",
    voiceAssistListening: "ಶ್ರವಣಿಸಲಾಗುತ್ತಿದೆ...",
    voiceAssistProcessing: "ಉತ್ತರ ಸಿದ್ಧಪಡಿಸಲಾಗುತ್ತಿದೆ...",
    voiceAssistResponded: "ಉತ್ತರ ಸಿದ್ಧ",
    voiceAssistError: "ಮೈಕ್ ಸಮಸ್ಯೆ",
    voiceAssistReady: "ಕೇಳಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    voiceAssistUnsupported: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಸಹಾಯ ಲಭ್ಯವಿಲ್ಲ.",
    voiceAssistTranscriptLabel: "ನೀವು ಕೇಳಿದದ್ದು",
    voiceAssistPromptExample: "ಉದಾಹರಣೆ: 'ಜಂಬೂ ಸವಾರಿ ಎಲ್ಲಿಂದ ಆರಂಭವಾಗುತ್ತದೆ?'",
    voiceAssistResponseLabel: "ಸಹಾಯಕನ ಉತ್ತರ",
    voiceAssistErrorDetail: "ಧ್ವನಿಯನ್ನು ಸೆರೆಹಿಡಿಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
    voiceAssistStopListening: "ನಿಲ್ಲಿಸಿ",
    voiceAssistTapToSpeak: "ಮಾತನಾಡಲು ಒತ್ತಿರಿ",
    voiceAssistStopAudio: "ಧ್ವನಿ ನಿಲ್ಲಿಸಿ",
    voiceAssistReplayAudio: "ಮತ್ತೆ ಕೇಳಿ",
    enableLocation: "ನಿಮ್ಮ ಹತ್ತಿರದ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಹುಡುಕಲು ಸ್ಥಳ ಹಂಚಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ!",
    locationDenied: "ಸ್ಥಳ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಎಲ್ಲಾ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    category: "ವರ್ಗ",
    time: "ಸಮಯ",
    directions: "ಮಾರ್ಗಗಳು",
    distance: "ದೂರ",
    duration: "ಅವಧಿ",
    routeNeedLocation: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಲು ಸ್ಥಳ ಹಂಚಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.",
    routeFetching: "ಉತ್ತಮ ಮಾರ್ಗವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    routeUnavailable: "ಈ ಕ್ಷಣ ಮಾರ್ಗ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    routeReady: "ನಡೆದಾಡಲು ಸೂಕ್ತ ಮಾರ್ಗ ಸಿದ್ಧವಾಗಿದೆ",
    clearRoute: "ಮಾರ್ಗವನ್ನು ಅಳಿಸಿ",
    busSupportTitle: "ಹತ್ತಿರದ KSRTC ನಗರ ಬಸ್ಸುಗಳು",
    busSupportSubtitle: "ಕಾರ್ಯಕ್ರಮ ಸ್ಥಳಕ್ಕೆ ಹತ್ತಿರದ ನಿಲ್ದಾಣಗಳನ್ನು ಬಳಸಿ.",
    busLoadingStatus: "ನಿಲ್ದಾಣಗಳನ್ನು ಹೊಂದಿಸಲಾಗುತ್ತಿದೆ...",
    busErrorStatus: "ಈ ಕ್ಷಣ ಬಸ್ ಜಾಲದ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ.",
    busListLabel: "ಬಸ್ಸುಗಳು",
    busNoStops: "ನಿಲ್ದಾಣಗಳ ಮಾಹಿತಿಯನ್ನು ಇನ್ನೂ ಸೇರಿಸಲಾಗಿಲ್ಲ.",
    eventVenueLabel: "ಸ್ಥಳ",
    searchPlaceholder: "ಕಾರ್ಯಕ್ರಮಗಳು ಅಥವಾ ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...",
    clearSearch: "ಅಳಿಸಿ",
    dayFilterLabel: "ದಿನ ಯಾವುದು?",
    allDays: "ಎಲ್ಲಾ ದಿನಗಳು",
    dayLabel: "ದಿನ",
    categoryFilterLabel: "ವರ್ಗ ಆಯ್ಕೆ",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    ageFilterLabel: "ವಯಸ್ಸಿನ ವರ್ಗ",
    allAgeGroups: "ಎಲ್ಲಾ ವಯಸ್ಸಿನ ಗುಂಪುಗಳು",
    statusLabel: "ಸ್ಥಿತಿ",
    statusLive: "ಪ್ರಸ್ತುತ",
    statusUpcoming: "ಬರುತ್ತಿದೆ",
    statusCompleted: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    routeInstructionsTitle: "ಹಂತ ಹಂತದ ಮಾರ್ಗ ಸೂಚನೆ",
    noInstructions: "ಈ ಮಾರ್ಗಕ್ಕೆ ವಿವರವಾದ ಸೂಚನೆಗಳಿಲ್ಲ.",
    routeRestrictionsTitle: "ಮಾರ್ಗ ಸಲಹೆಗಳು",
    noRestrictions: "ಈ ಮಾರ್ಗದಲ್ಲಿ ಯಾವುದೇ ನಿರ್ಬಂಧಗಳಿಲ್ಲ.",
    activeOnDays: "ಸಕ್ರಿಯ ದಿನಗಳು",
    restrictionRadius: "ನಿರ್ಬಂಧಿತ ವ್ಯಾಪ್ತಿ",
    metersUnit: "ಮೀ",
    kilometersUnit: "ಕಿ.ಮೀ",
    secondsUnitShort: "ಸೆ",
    minutesUnitShort: "ನಿ",
    jambooStartLabel: "ಮೈಸೂರು ಅರಮನೆ – ಬಾಲರಾಮ ಬಾಗಿಲು",
    jambooEndLabel: "ಬನ್ನಿಮಂಟಪ ಮೈದಾನ",
    jambooRouteLabel: "ದಸರಾ ಮೆರವಣಿಗೆ ಮಾರ್ಗ",
    processionRouteTitle: "ಜಂಬೂ ಸವಾರಿ ಮೆರವಣಿಗೆ",
    processionRouteSubtitle: "ಮೈಸೂರು ಅರಮನೆಯಿಂದ ಬನ್ನಿಮಂಟಪ ಮೈದಾನವರೆಗಿನ ಮಾರ್ಗ",
    processionFocusCta: "ಮಾರ್ಗ ತೋರಿಸಿ",
    processionStopsHeading: "ಪ್ರಮುಖ ಮಾರ್ಗ ಹಂತಗಳು",
    processionStartingPoint: "ಆರಂಭಿಕ ಸ್ಥಳ",
    processionEndingPoint: "ಅಂತಿಮ ಸ್ಥಳ",
    processionCardMapView: "ನಕ್ಷೆ ವೀಕ್ಷಣೆ",
    processionCardShow: "ಕಾರ್ಡ್ ತೋರಿಸಿ",
    showClosures: "ರಸ್ತೆ ಬಂದ್ ಸ್ಥಳಗಳು",
    hideClosures: "ರಸ್ತೆ ಬಂದ್ ಮರೆಮಾಡಿ",
    closuresTitle: "ರಸ್ತೆ ಬಂದ್ ವಿವರಗಳು",
    noEvents: "ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ.",
    noEventsForDay: "ದಿನಕ್ಕೆ ಯಾವುದೇ ಕಾರ್ಯಕ್ರಮವಿಲ್ಲ",
    noSearchResults: "ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದಿಕೆಯಿಲ್ಲ",
    searchHint: "ಬೇರೆ ಹೆಸರು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅಳಿಸಿ ಎಲ್ಲಾ ಸ್ಥಳಗಳನ್ನು ನೋಡಿ.",
    noFilterResults: "ಆಯ್ದ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ."
  },
  hi: {
    title: "दसरा मित्र",
    heroTitle: "मैसूरु दशहरा में आपका स्वागत है",
    heroSubtitle: "आपका उत्सव साथी – कार्यक्रम, यात्रा और यादों को सहज बनाएं।",
    ctaEvents: "पास के कार्यक्रम",
    ctaGallery: "गैलरी देखें",
    eventsTitle: "उत्सव कार्यक्रम मानचित्र",
    eventsHeroDescription: "मुख्य मैसूरु दशहरा झलकियाँ खोजें, उनके सटीक स्थान पिन करें और निकलने से पहले समय की जानकारी पाएं।",
    transportTitle: "यातायात मार्ग योजनाकार",
    transportHeroDescription: "बस, टैक्सी और ऑटो के त्वरित यात्रा आकलनों के साथ अपने स्थल-दर-स्थल सफ़र की योजना बनाएँ।",
    galleryTitle: "फोटो गैलरी",
    galleryHeroDescription: "महल की रोशनियों से चामुंडी पहाड़ी के नज़ारों तक सुनहरी दशहरा यादों को फिर से जिएँ।",
    galleryFallbackTitle: "उत्सव की खास झलकियाँ",
    galleryFallbackBlurb: "महल की रोशनी, जुलूस और सांस्कृतिक माहौल की झलक।",
    galleryLoadingMessage: "Cloudinary से उत्सव की तस्वीरें लोड हो रही हैं...",
    galleryCloudinaryEmpty: "निर्धारित टैग के लिए Cloudinary ने कोई तस्वीर नहीं लौटाई। अब डिफ़ॉल्ट गैलरी दिखा रहे हैं।",
    galleryCloudinaryError: "अभी Cloudinary गैलरी लोड नहीं हो सकी। फिलहाल डिफ़ॉल्ट तस्वीरें दिखा रहे हैं।",
    galleryNoImages: "{{section}} के लिए अभी कोई तस्वीर अपलोड नहीं हुई है।",
    gallerySectionPalaceTitle: "मैसूरु महल",
    gallerySectionPalaceBlurb: "रोशनी, रीतियों और राजसी दृश्य की झलक।",
    gallerySectionFlowerTitle: "फूल प्रदर्शनी",
    gallerySectionFlowerBlurb: "कुप्पन्ना पार्क की पुष्प कलाकृतियाँ और सजावट।",
    gallerySectionProcessionTitle: "जम्बू सवारी जुलूस",
    gallerySectionProcessionBlurb: "सय्याजी राव रोड पर भव्य समापन क्षण।",
    gallerySectionLightingsTitle: "शहर की रोशनी",
    gallerySectionLightingsBlurb: "विरासत वाली गलियाँ झिलमिलाती सजावट में।",
    gallerySectionCulturalTitle: "सांस्कृतिक गतिविधियाँ",
    gallerySectionCulturalBlurb: "युवा दशहरा मंचों से संगीत, नृत्य और नाटक।",
    gallerySectionYuvaTitle: "युवा दशहरा",
    gallerySectionYuvaBlurb: "मेसूरु भर में युवा कॉन्सर्ट और देर रात कार्यक्रम।",
    gallerySectionChamundiTitle: "चामुंडी मंदिर",
    gallerySectionChamundiBlurb: "चामुंडी पहाड़ी पर आध्यात्मिक शांति।",
    gallerySectionExhibitionTitle: "दशहरा प्रदर्शनी",
    gallerySectionExhibitionBlurb: "दोड्डकेरे मैदान में दुकानें, झूले और यादें।",
    gallerySectionTableauTitle: "प्रोसेशन टेबलो",
    gallerySectionTableauBlurb: "जम्बू सवारी में मैसूरु धरोहर दिखाते कलात्मक झाँकियाँ।",
    gallerySectionWrestlingTitle: "कुश्ती प्रतियोगिता",
    gallerySectionWrestlingBlurb: "नाडा कुश्ती अखाड़े में चैंपियन पहलवानों की भिड़ंत।",
    gallerySectionDroneTitle: "ड्रोन लाइट शो",
    gallerySectionDroneBlurb: "ललिता महल के आसमान में सजी समन्वित प्रकाश कथाएँ।",
    gallerySectionVintageTitle: "विंटेज कार रैली",
    gallerySectionVintageBlurb: "मैसूरु महल से ललिता महल तक दौड़ती क्लासिक कारों की शोभायात्रा।",
    footerEventsCardDescription: "हर मैसूरु उत्सव को पिन करें और शाही कार्यक्रम सूची में डूबें।",
    footerTransportCardDescription: "विकल्प मार्ग, शटल और उत्सव यात्रा को भरोसे से योजना करें।",
    footerGalleryCardDescription: "महल की रोशनियाँ और सांस्कृतिक यादें तुरंत फिर से जीएँ।",
    footerExploreCta: "और जानें",
    home: "मुखपृष्ठ",
    events: "कार्यक्रम",
    transport: "यातायात",
    gallery: "गैलरी",
    findRoute: "मार्ग खोजें",
    fromEvent: "यहाँ से",
    toEvent: "यहाँ तक",
    calculating: "गणना जारी...",
    routeDetails: "मार्ग विवरण",
    footerText: HI_FOOTER_COPY,
    footerAboutTitle: "दसरा मित्र के बारे में",
    footerAboutDescription: "मैसूर दशहरा के दौरान मार्गों, कार्यक्रमों और ज़रूरी जानकारी के लिए आपका द्विभाषी मार्गदर्शक।",
    footerDiscoverTitle: "दशहरा खोजें",
    footerVisitTitle: "अपनी यात्रा योजना",
    footerContactTitle: "उत्सव हेल्पडेस्क",
    footerContactPhoneLabel: "हेल्पलाइन",
    footerContactPhoneValue: "+91 78931XXXXX",
    footerContactEmailLabel: "ईमेल",
    footerContactEmailValue: "artappreciating@gmail.com",
    footerContactHoursLabel: "समय",
    footerContactHoursValue: "प्रतिदिन सुबह 9 – रात 10 (IST)",
    footerContactOfficeLabel: "कमांड केंद्र",
    footerContactOfficeValue: "दशहरा प्रदर्शनी मैदान, मैसूरु",
    footerConnectTitle: "संपर्क में रहें",
    footerAddress: "मैसूरु, कर्नाटक, भारत",
    footerDisclaimer: "समुदाय द्वारा बनाया गया साथी। जानकारी मैसूरु दशहरा प्राधिकरण से सत्यापित है।",
    footerFestivalDates: HI_FESTIVAL_DATES,
    footerPlanTip: "भव्य जम्बू सवारी में अच्छा दृश्य पाने के लिए शाम 4 बजे तक पहुँचें।",
    footerDailyFlowTitle: "दैनिक उत्सव क्रम",
    footerDailyFlowDescription: "हर दिन की मुख्य झलक जानें और कोई विशेष क्षण न चूकें।",
    footerSocialTitle: "उत्सव को फ़ॉलो करें",
    footerSocialInstagram: "इंस्टाग्राम",
    footerSocialYoutube: "यूट्यूब",
    footerSocialFacebook: "फेसबुक",
    footerSocialX: "एक्स (ट्विटर)",
    footerNewsletterTitle: "उत्सव समाचारपत्र",
    footerNewsletterDescription: "हर दिन की मुख्य बातें, मार्ग अपडेट और सांस्कृतिक झलक सीधे अपने इनबॉक्स में पाएं।",
    footerNewsletterPlaceholder: "अपना ईमेल दर्ज करें",
    footerNewsletterCta: "मुझे अपडेट करें",
    footerNewsletterDisclaimer: "कोई स्पैम नहीं। कभी भी सदस्यता समाप्त करें। अपडेट केवल उत्सव सप्ताह में भेजे जाएँगे।",
    contactFormTitle: "हेल्पडेस्क को संदेश भेजें",
    contactFormDescription: "अपना सवाल लिखें, हम इसे दशहरा कंट्रोल रूम तक पहुँचाएंगे।",
    contactFormNameLabel: "पूरा नाम",
    contactFormEmailLabel: "ईमेल पता",
    contactFormMessageLabel: "संदेश",
    contactFormSubmitLabel: "संदेश भेजें",
    contactFormSendingLabel: "भेजा जा रहा है...",
    contactFormSuccess: "धन्यवाद! आपका संदेश हेल्पडेस्क तक पहुँच गया है।",
    contactFormError: "अभी संदेश भेजा नहीं जा सका। कृपया थोड़ी देर बाद प्रयास करें।",
    contactFormSettingsError: "ईमेल सेवा कॉन्फ़िगर नहीं है। कृपया EmailJS पर्यावरण मान जोड़ें।",
    contactFormValidationError: "भेजने से पहले अपना नाम, मान्य ईमेल और संदेश जरूर भरें।",
    nearest: "आपके पास",
    chatTitle: "दसरा सहायक",
    chatPlaceholder: "कार्यक्रम, मार्ग या इतिहास पूछें...",
    send: "भेजें",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया।",
    voiceAssistTitle: "वॉयस सहायक",
    voiceAssistHint: "माइक टैप करें और मार्ग या कार्यक्रमों के बारे में पूछें।",
    voiceAssistListening: "सुन रहा है...",
    voiceAssistProcessing: "उत्तर तैयार किया जा रहा है...",
    voiceAssistResponded: "उत्तर तैयार है",
    voiceAssistError: "माइक समस्या",
    voiceAssistReady: "पूछने के लिए टैप करें",
    voiceAssistUnsupported: "इस ब्राउज़र में वॉयस सहायता उपलब्ध नहीं है।",
    voiceAssistTranscriptLabel: "आपने पूछा",
    voiceAssistPromptExample: "उदाहरण: 'जम्बू सवारी कहाँ से शुरू होती है?'",
    voiceAssistResponseLabel: "सहायक का उत्तर",
    voiceAssistErrorDetail: "ध्वनि कैप्चर नहीं हो सकी",
    voiceAssistStopListening: "रोकें",
    voiceAssistTapToSpeak: "बोलने के लिए टैप करें",
    voiceAssistStopAudio: "ध्वनि रोकें",
    voiceAssistReplayAudio: "फिर से सुनें",
    enableLocation: "पास के कार्यक्रम खोजने के लिए स्थान सक्षम करें!",
    locationDenied: "स्थान पहुंच अस्वीकृत। सभी कार्यक्रम दिखाए जा रहे हैं।",
    category: "श्रेणी",
    time: "समय",
    directions: "दिशाएँ",
    distance: "दूरी",
    duration: "अवधि",
    routeNeedLocation: "दिशाएँ पाने के लिए स्थान सक्षम करें।",
    routeFetching: "सबसे अच्छा मार्ग खोजा जा रहा है...",
    routeUnavailable: "अभी मार्ग उपलब्ध नहीं है। कृपया कुछ देर बाद प्रयास करें।",
    routeReady: "पैदल मार्ग तैयार",
    clearRoute: "मार्ग हटाएँ",
    busSupportTitle: "निकटतम KSRTC सिटी बसें",
    busSupportSubtitle: "कार्यक्रम स्थल के सबसे पास के स्टॉप का उपयोग करें।",
    busLoadingStatus: "स्टॉप जोड़े जा रहे हैं...",
    busErrorStatus: "अभी बस नेटवर्क उपलब्ध नहीं है।",
    busListLabel: "बसें",
    busNoStops: "कोई स्टॉप मैप नहीं किए गए।",
    eventVenueLabel: "स्थान",
    searchPlaceholder: "कार्यक्रम या श्रेणी खोजें...",
    clearSearch: "साफ करें",
    dayFilterLabel: "दिन से फ़िल्टर करें",
    allDays: "सभी दिन",
    dayLabel: "दिन",
    categoryFilterLabel: "श्रेणी द्वारा फ़िल्टर",
    allCategories: "सभी श्रेणियाँ",
    ageFilterLabel: "आयु वर्ग",
    allAgeGroups: "सभी आयु समूह",
    statusLabel: "स्थिति",
    statusLive: "चल रहा है",
    statusUpcoming: "आने वाला",
    statusCompleted: "समाप्त",
    routeInstructionsTitle: "चरण-दर-चरण निर्देश",
    noInstructions: "इस मार्ग के लिए विस्तृत निर्देश उपलब्ध नहीं हैं।",
    routeRestrictionsTitle: "मार्ग सलाह",
    noRestrictions: "इस मार्ग पर कोई प्रतिबंध नहीं।",
    activeOnDays: "सक्रिय दिन",
    restrictionRadius: "प्रतिबंधित त्रिज्या",
    metersUnit: "मीटर",
    kilometersUnit: "किमी",
    secondsUnitShort: "से",
    minutesUnitShort: "मि",
    jambooStartLabel: "मैसूरु पैलेस – बालारामा गेट",
    jambooEndLabel: "बन्नीमंतप मैदान",
    jambooRouteLabel: "भव्य जम्बू सवारी मार्ग",
    processionRouteTitle: "जम्बू सवारी जुलूस",
    processionRouteSubtitle: "मैसूरु पैलेस से बन्नीमंतप मैदान तक",
    processionFocusCta: "मार्ग दिखाएँ",
    processionStopsHeading: "मुख्य पड़ाव",
    processionStartingPoint: "प्रारंभिक स्थान",
    processionEndingPoint: "समाप्ति स्थान",
    processionCardMapView: "मैप दृश्य",
    processionCardShow: "कार्ड दिखाएँ",
    showClosures: "सड़क अवरोध दिखाएँ",
    hideClosures: "सड़क अवरोध छिपाएँ",
    closuresTitle: "सड़क अवरोध",
    noEvents: "कोई कार्यक्रम उपलब्ध नहीं।",
    noEventsForDay: "इस दिन के लिए कोई कार्यक्रम नहीं",
    noSearchResults: "का कोई परिणाम नहीं",
    searchHint: "दूसरा नाम आज़माएँ या सभी कार्यक्रम देखने के लिए फ़िल्टर हटाएँ।",
    noFilterResults: "चयनित फ़िल्टर से कोई कार्यक्रम मेल नहीं खाता।"
  }
};

const SUPPORTED_LANGUAGES = ['en', 'kn', 'hi'];
const LANGUAGE_LABELS = {
  en: 'EN',
  kn: 'ಕನ್ನಡ',
  hi: 'हिं'
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(SUPPORTED_LANGUAGES[0]);

  const t = (key) => {
    return TRANSLATIONS[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguageState((prev) => {
      const currentIndex = SUPPORTED_LANGUAGES.indexOf(prev);
      const nextIndex = (currentIndex + 1) % SUPPORTED_LANGUAGES.length;
      return SUPPORTED_LANGUAGES[nextIndex];
    });
  };

  const setLanguage = (nextLanguage) => {
    if (!SUPPORTED_LANGUAGES.includes(nextLanguage)) {
      return;
    }
    setLanguageState(nextLanguage);
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        toggleLanguage,
         setLanguage,
        t,
        languageLabel: LANGUAGE_LABELS[language],
        supportedLanguages: SUPPORTED_LANGUAGES
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);