import React, { createContext, useContext, useState } from 'react';

export const EVENTS_DATA = [
  {
    id: 1,
    name: "Jumboo Savari",
    name_kn: "ಜಂಬೂ ಸವಾರಿ",
    lat: 12.3051,
    lng: 76.6551,
    description: "The grand elephant procession marking the finale of Dasara.",
    description_kn: "ದಸರಾ ಹಬ್ಬದ ಅಂತ್ಯವನ್ನು ಗುರುತಿಸುವ ಪ್ರಮುಖ ಆನೆ ಮೆರವಣಿಗೆ.",
    time: "Oct 12, 2:30 PM",
    category: "Parade",
    day: 10,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 2,
    name: "Torchlight Parade",
    name_kn: "ಪಂಜಿನ ಕವಾಯತು",
    lat: 12.3225,
    lng: 76.6589,
    description: "A spectacular display of lights and military drills at Bannimantap.",
    description_kn: "ಬನ್ನಿಮಂಟಪದಲ್ಲಿ ದೀಪಗಳು ಮತ್ತು ಸೇನಾ ಕವಾಯತಿನ ಅದ್ಭುತ ಪ್ರದರ್ಶನ.",
    time: "Oct 12, 7:00 PM",
    category: "Parade",
    day: 9,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 3,
    name: "Mysore Palace Illumination",
    name_kn: "ಮೈಸೂರು ಅರಮನೆ ದೀಪಾಲಂಕಾರ",
    lat: 12.3052,
    lng: 76.6552,
    description: "The palace lit up with nearly 100,000 bulbs.",
    description_kn: "ಸುಮಾರು ೧ ಲಕ್ಷ ದೀಪಗಳಿಂದ ಬೆಳಗುವ ಅರಮನೆ.",
    time: "Daily, 7:00 PM",
    category: "Sightseeing",
    day: 1,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 4,
    name: "Dasara Exhibition",
    name_kn: "ದಸರಾ ವಸ್ತುಪ್ರದರ್ಶನ",
    lat: 12.3020,
    lng: 76.6600,
    description: "Shopping, food, and entertainment stalls opposite the palace.",
    description_kn: "ಅರಮನೆಯ ಎದುರು ಶಾಪಿಂಗ್, ಊಟ ಮತ್ತು ಮನರಂಜನೆ ಮಳಿಗೆಗಳು.",
    time: "Daily, 10:00 AM - 9:00 PM",
    category: "Fair",
    day: 2,
    status: 'live',
    ageGroup: 'Family',
    ageGroup_kn: 'ಕುಟುಂಬ'
  },
  {
    id: 5,
    name: "Flower Show",
    name_kn: "ಫಲಪುಷ್ಪ ಪ್ರದರ್ಶನ",
    lat: 12.3000,
    lng: 76.6700,
    description: "Exotic floral arrangements at Kuppanna Park.",
    description_kn: "ಕುಪ್ಪಣ್ಣ ಪಾರ್ಕ್‌ನಲ್ಲಿ ವಿಲಕ್ಷಣ ಹೂವಿನ ಅಲಂಕಾರಗಳು.",
    time: "Daily, 9:00 AM - 9:00 PM",
    category: "Nature",
    day: 3,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 6,
    name: "Yuva Dasara",
    name_kn: "ಯುವ ದಸರಾ",
    lat: 12.3100,
    lng: 76.6300,
    description: "Concerts and youth cultural programs at Maharaja's College Grounds.",
    description_kn: "ಮಹಾರಾಜ ಕಾಲೇಜು ಮೈದಾನದಲ್ಲಿ ಸಂಗೀತ ಮತ್ತು ಯುವ ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು.",
    time: "Oct 6-10, 6:00 PM",
    category: "Music",
    day: 5,
    status: 'live',
    ageGroup: 'Youth',
    ageGroup_kn: 'ಯುವ'
  },
  {
    id: 7,
    name: "Wrestling Tournament",
    name_kn: "ಕುಸ್ತಿ ಪಂದ್ಯಾವಳಿ",
    lat: 12.3080,
    lng: 76.6500,
    description: "Traditional Nada Kusti wrestling matches.",
    description_kn: "ಸಾಂಪ್ರದಾಯಿಕ ನಾಡ ಕುಸ್ತಿ ಪಂದ್ಯಗಳು.",
    time: "Oct 5-9, 4:00 PM",
    category: "Sports",
    day: 6,
    status: 'live',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು'
  },
  {
    id: 8,
    name: "Poets' Conference (Kavi Goshti)",
    name_kn: "ಕವಿ ಗೋಷ್ಠಿ",
    lat: 12.3040,
    lng: 76.6530,
    description: "Gathering of renowned poets and literature lovers.",
    description_kn: "ಪ್ರಖ್ಯಾತ ಕವಿಗಳು ಮತ್ತು ಸಾಹಿತ್ಯ ಪ್ರೇಮಿಗಳ ಸಭೆ.",
    time: "Oct 7, 10:00 AM",
    category: "Culture",
    day: 4,
    status: 'completed',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು'
  },
  {
    id: 9,
    name: "Food Mela (Ahaara Mela)",
    name_kn: "ಆಹಾರ ಮೇಳ",
    lat: 12.2990,
    lng: 76.6450,
    description: "Traditional delicacies from across Karnataka.",
    description_kn: "ಕರ್ನಾಟದಾದ್ಯಂತದ ಸಾಂಪ್ರದಾಯಿಕ ಖಾದ್ಯಗಳು.",
    time: "Daily, 11:00 AM - 10:00 PM",
    category: "Food",
    day: 7,
    status: 'live',
    ageGroup: 'Family',
    ageGroup_kn: 'ಕುಟುಂಬ'
  },
  {
    id: 10,
    name: "Cultural Programs at Palace",
    name_kn: "ಅರಮನೆಯಲ್ಲಿ ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು",
    lat: 12.3051,
    lng: 76.6551,
    description: "Classical music and dance performances in front of the illuminated palace.",
    description_kn: "ದೀಪಾಲಂಕೃತ ಅರಮನೆಯ ಮುಂಭಾಗದಲ್ಲಿ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಮತ್ತು ನೃತ್ಯ ಪ್ರದರ್ಶನಗಳು.",
    time: "Daily, 6:00 PM",
    category: "Culture",
    day: 8,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 11,
    name: "Drone Light Show",
    name_kn: "ಡ್ರೋನ್ ಬೆಳಕು ಪ್ರದರ್ಶನ",
    lat: 12.295,
    lng: 76.681,
    description: "Synchronized drones create immersive formations above Lalitha Mahal grounds.",
    description_kn: "ಲಲಿತಾ ಮಹಲ್ ಮೈದಾನದ ಮೇಲೆ ಡ್ರೋನ್‌ಗಳು ಅದ್ಭುತ ವಿನ್ಯಾಸಗಳನ್ನು ನಿರ್ಮಿಸುತ್ತವೆ.",
    time: "Oct 8-10, 8:30 PM",
    category: "Light Show",
    day: 9,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 12,
    name: "Heritage Street Performances",
    name_kn: "ಪಾರಂಪರಿಕ ರಸ್ತೆ ಪ್ರದರ್ಶನಗಳು",
    lat: 12.3074,
    lng: 76.6529,
    description: "Traditional folk artists take over the illuminated Devaraja Market streets.",
    description_kn: "ಅಲಂಕೃತ ದೇವರಾಜ ಮಾರುಕಟ್ಟೆ ರಸ್ತೆಯಲ್ಲಿ ಪಾರಂಪರಿಕ ಜನಪದ ಕಲಾವಿದರು ಪ್ರದರ್ಶನ ನೀಡುತ್ತಾರೆ.",
    time: "Daily, 6:00 PM - 9:00 PM",
    category: "Culture",
    day: 4,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 13,
    name: "Makkala Dasara",
    name_kn: "ಮಕ್ಕಳ ದಸರಾ",
    lat: 12.3152,
    lng: 76.6308,
    description: "Interactive workshops, storytelling corners, and science demos for children.",
    description_kn: "ಮಕ್ಕಳಿಗಾಗಿ ಕಾರ್ಯಾಗಾರಗಳು, ಕಥೆ ಹೇಳುವ ಮೂಲೆಗಳು ಮತ್ತು ವಿಜ್ಞಾನ ಪ್ರದರ್ಶನಗಳು.",
    time: "Oct 4-6, 10:00 AM - 5:00 PM",
    category: "Kids",
    day: 3,
    status: 'completed',
    ageGroup: 'Kids',
    ageGroup_kn: 'ಮಕ್ಕಳು'
  },
  {
    id: 14,
    name: "Raitha Dasara",
    name_kn: "ರೈತ ದಸರಾ",
    lat: 12.3286,
    lng: 76.6548,
    description: "Farmer felicitation, agri-tech demos, and organic produce fair at JSS Grounds.",
    description_kn: "ಜಿಎಸ್‌ಎಸ್ ಮೈದಾನದಲ್ಲಿ ರೈತರ ಸನ್ಮಾನ, ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ ಪ್ರದರ್ಶನ ಮತ್ತು ಸಾವಯವ ಮಾರುಕಟ್ಟೆ.",
    time: "Oct 5-7, 9:00 AM - 6:00 PM",
    category: "Agriculture",
    day: 4,
    status: 'completed',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು'
  },
  {
    id: 15,
    name: "Vintage Car Rally",
    name_kn: "ವಿಂಟೇಜ್ ಕಾರು ರ‍್ಯಾಲಿ",
    lat: 12.3091,
    lng: 76.6577,
    description: "Classic cars parade from the palace to Lalitha Mahal with live commentary.",
    description_kn: "ಅರಮನೆದಿಂದ ಲಲಿತಾ ಮಹಲ್‌ವರೆಗೆ ವಿಂಟೇಜ್ ಕಾರುಗಳ ಮೆರವಣಿಗೆ ಮತ್ತು ಸಜೀವ ವಿವರಣೆ.",
    time: "Oct 6, 7:30 AM",
    category: "Lifestyle",
    day: 5,
    status: 'completed',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 16,
    name: "Yoga by the Palace",
    name_kn: "ಅರಮನೆ ಬಳಿ ಯೋಗ",
    lat: 12.3046,
    lng: 76.6555,
    description: "Sunrise yoga sessions led by renowned instructors with palace backdrop.",
    description_kn: "ಪರಿಚಿತ ಶಿಕ್ಷಕರಿಂದ ಅರಮನೆ ಹಿನ್ನೆಲೆಯೊಂದಿಗೆ ಸೂರ್ಯೋದಯ ಯೋಗ ಶಿಬಿರ.",
    time: "Oct 3-9, 6:00 AM",
    category: "Wellness",
    day: 2,
    status: 'live',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು'
  },
  {
    id: 17,
    name: "Folk Dance Utsav",
    name_kn: "ಜನಪದ ನೃತ್ಯ ಉತ್ಸವ",
    lat: 12.3121,
    lng: 76.6469,
    description: "Teams from across Karnataka perform vibrant folk dances at Town Hall.",
    description_kn: "ಕರ್ನಾಟಕದ ವಿವಿಧ ತಂಡಗಳು ಟೌನ್ ಹಾಲ್‌ನಲ್ಲಿ ಚೆಲುವಾದ ಜನಪದ ನೃತ್ಯ ಪ್ರದರ್ಶನ ನೀಡುತ್ತವೆ.",
    time: "Oct 7-9, 5:00 PM - 8:00 PM",
    category: "Dance",
    day: 6,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು'
  },
  {
    id: 18,
    name: "Adventure Sports Zone",
    name_kn: "ಸಾಹಸ ಕ್ರೀಡೆ ವಲಯ",
    lat: 12.2995,
    lng: 76.6672,
    description: "Ziplining, wall climbing, and obstacle courses at Chamundi Vihar Stadium.",
    description_kn: "ಚಾಮುಂಡಿ ವಿಹಾರ ಕ್ರೀಡಾಂಗಣದಲ್ಲಿ ಜಿಪ್‌ಲೈನ್, ಗೋಡೆ ಏರಿಕೆ ಮತ್ತು ಅಡೆತಡೆ ಆಟಗಳು.",
    time: "Oct 5-10, 10:00 AM - 7:00 PM",
    category: "Adventure",
    day: 7,
    status: 'live',
    ageGroup: 'Youth',
    ageGroup_kn: 'ಯುವ'
  }
];

export const ROAD_CLOSURES = [
  {
    id: 'closure-palace-road',
    name: 'Palace Road Barricade',
    name_kn: 'ಅರಮನೆ ರಸ್ತೆ ಅಡ್ಡಿ',
    lat: 12.3058,
    lng: 76.6558,
    description: 'Access closed for parade rehearsal from 1 PM - 8 PM.',
    description_kn: 'ಮೆರವಣಿಗೆ ಅಭ್ಯಾಸದ ಕಾರಣ ಮಧ್ಯಾಹ್ನ ೧ ರಿಂದ ರಾತ್ರಿ ೮ರವರೆಗೆ ಪ್ರವೇಶ ಮುಚ್ಚಲಾಗಿದೆ.',
    days: [9, 10],
    radius: 220
  },
  {
    id: 'closure-bannimantap',
    name: 'Bannimantap Grounds Diversion',
    name_kn: 'ಬನ್ನಿಮಂಟಪ ದಾರಿದೀಪ ಬದಲಾವಣೆ',
    lat: 12.3185,
    lng: 76.6572,
    description: 'Night traffic diverted for torchlight rehearsal 6 PM - 10 PM.',
    description_kn: 'ಟಾರ್ಚ್‌ಲೈಟ್ ಅಭ್ಯಾಸಕ್ಕಾಗಿ ರಾತ್ರಿ ೬ ರಿಂದ ೧೦ರವರೆಗೆ ವಾಹನ ಸಂಚಾರ ಮತ್ತೊಂದು ಮಾರ್ಗಕ್ಕೆ ಪರಿವರ್ತನೆ.',
    days: [8, 9, 10],
    radius: 180
  },
  {
    id: 'closure-doddakere',
    name: 'Doddakere Maidan Parking Restriction',
    name_kn: 'ದೊಡ್ಡಕೆರೆ ಮೈದಾನ ವಾಹನ ನಿಲುಗಡೆ ನಿರ್ಬಂಧ',
    lat: 12.3036,
    lng: 76.6579,
    description: 'Only shuttle buses allowed between 9 AM - 11 PM.',
    description_kn: 'ಬೆಳಿಗ್ಗೆ ೯ರಿಂದ ರಾತ್ರಿ ೧೧ರವರೆಗೆ ಶಟಲ್ ಬಸ್ಸುಗಳಿಗೆ ಮಾತ್ರ ಅನುಮತಿ.',
    days: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    radius: 160
  },
  {
    id: 'closure-jamboo-route',
    name: 'Jamboo Savari Procession Route',
    name_kn: 'ಜಂಬೂ ಸವಾರಿ ಮೆರವಣಿಗೆ ಮಾರ್ಗ',
    lat: 12.3198,
    lng: 76.6607,
    description: 'Entire 5 km corridor from Mysuru Palace (Balarama Gate) to Bannimantap Grounds closed for vehicles from 8 AM - 8 PM on the grand finale day.',
    description_kn: 'ಅಂತಿಮ ದಿನ ಬೆಳಿಗ್ಗೆ ೮ ರಿಂದ ರಾತ್ರಿ ೮ರವರೆಗೆ ಮೈಸೂರು ಅರಮನೆ (ಬಾಲರಾಮ ದಿಂದ)ದಿಂದ ಬನ್ನಿಮಂಟಪ ಮೈದಾನವರೆಗೆ ೫ ಕಿಮೀ ಮಾರ್ಗವು ಎಲ್ಲಾ ವಾಹನಗಳಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಮುಚ್ಚಲ್ಪಟ್ಟಿದೆ.',
    days: [10],
    radius: 120,
    pathBuffer: 250,
    path: [
      { lat: 12.305163, lng: 76.6551749 },
      { lat: 12.30568, lng: 76.65594 },
      { lat: 12.30664, lng: 76.6569 },
      { lat: 12.30775, lng: 76.65793 },
      { lat: 12.30894, lng: 76.65848 },
      { lat: 12.31012, lng: 76.65841 },
      { lat: 12.31193, lng: 76.65766 },
      { lat: 12.31375, lng: 76.65705 },
      { lat: 12.31568, lng: 76.65647 },
      { lat: 12.31752, lng: 76.65602 },
      { lat: 12.31913, lng: 76.65566 },
      { lat: 12.32074, lng: 76.65545 },
      { lat: 12.32247, lng: 76.65531 },
      { lat: 12.32428, lng: 76.6552 },
      { lat: 12.32606, lng: 76.65512 },
      { lat: 12.32782, lng: 76.65504 },
      { lat: 12.32959, lng: 76.655 },
      { lat: 12.33147, lng: 76.65499 },
      { lat: 12.33328, lng: 76.65499 },
      { lat: 12.3340167, lng: 76.6549883 }
    ]
  }
];

export const TRANSLATIONS = {
  en: {
    title: "Dasara Mitra",
    heroTitle: "Welcome to Mysore Dasara 2025",
    heroSubtitle: "Your Festival Companion – Navigate events, transport, and memories effortlessly.",
    ctaEvents: "Find Nearest Events",
    ctaGallery: "Explore Gallery",
    eventsTitle: "Festival Events Map",
    transportTitle: "Transport Route Planner",
    galleryTitle: "Photo Gallery",
    home: "Home",
    events: "Events",
    transport: "Transport",
    gallery: "Gallery",
    findRoute: "Find Route",
    fromEvent: "From Event",
    toEvent: "To Event",
    calculating: "Calculating...",
    routeDetails: "Route Details",
    footerText: "© 2025 Dasara Mitra. Celebrating the spirit of Mysore.",
    footerAboutTitle: "About Dasara Mitra",
    footerAboutDescription: "Your bilingual festival navigator for routes, events, and on-ground essentials during Mysuru Dasara.",
    footerDiscoverTitle: "Discover Dasara",
    footerVisitTitle: "Plan your visit",
    footerConnectTitle: "Stay in touch",
    footerAddress: "Mysuru, Karnataka, India",
    footerDisclaimer: "Community-built companion. Information verified with Mysuru Dasara authorities.",
    footerFestivalDates: "Navaratri • 1 – 10 Oct 2025",
    footerPlanTip: "Arrive by 4 PM to secure vantage points for the grand Jamboo Savari procession.",
    footerSocialTitle: "Follow the celebrations",
    footerSocialInstagram: "Instagram",
    footerSocialYoutube: "YouTube",
    footerSocialFacebook: "Facebook",
    footerSocialX: "X (Twitter)",
    footerNewsletterTitle: "Festival bulletin",
    footerNewsletterDescription: "Get daily highlights, road updates, and exclusive cultural insights in your inbox.",
    footerNewsletterPlaceholder: "Enter your email",
    footerNewsletterCta: "Keep me updated",
    footerNewsletterDisclaimer: "No spam. Unsubscribe anytime. Updates shared during festival week.",
    nearest: "Nearest to you",
    chatTitle: "Dasara Helper",
    chatPlaceholder: "Ask about events, routes, or history...",
    send: "Send",
    loading: "Loading...",
    error: "Something went wrong.",
    enableLocation: "Enable location to find events near you!",
    locationDenied: "Location access denied. Showing all events.",
    category: "Category",
    time: "Time",
    directions: "Get Directions",
    distance: "Distance",
    duration: "Duration",
    routeNeedLocation: "Enable location to get directions.",
    routeFetching: "Fetching the best route...",
    routeUnavailable: "Route unavailable right now. Please try again in a moment.",
    routeReady: "Walking route ready",
    clearRoute: "Clear Route",
    searchPlaceholder: "Search events or categories...",
    clearSearch: "Clear",
    dayFilterLabel: "Filter by day",
    allDays: "All days",
    dayLabel: "Day",
    categoryFilterLabel: "Filter by category",
    allCategories: "All categories",
    ageFilterLabel: "Age category",
    allAgeGroups: "All age groups",
    statusLabel: "Status",
    statusLive: "Live",
    statusUpcoming: "Upcoming",
    statusCompleted: "Completed",
    routeInstructionsTitle: "Turn-by-turn directions",
    noInstructions: "Detailed steps are unavailable for this route.",
    routeRestrictionsTitle: "Route advisories",
    noRestrictions: "No restrictions along this route.",
    activeOnDays: "Active on days",
    restrictionRadius: "Restricted radius",
    metersUnit: "m",
    kilometersUnit: "km",
    secondsUnitShort: "sec",
    minutesUnitShort: "min",
    jambooStartLabel: "Mysuru Palace – Balarama Gate",
    jambooEndLabel: "Bannimantap Grounds",
    jambooRouteLabel: "Grand Procession Corridor",
    showClosures: "Show road blockages",
    hideClosures: "Hide road blockages",
    closuresTitle: "Road blockages",
    noEvents: "No events available.",
    noEventsForDay: "No events scheduled for Day",
    noSearchResults: "No matches for",
    searchHint: "Try a different event name or clear the filters to explore everything.",
    noFilterResults: "No events match the selected filters."
  },
  kn: {
    title: "ದಸರಾ ಮಿತ್ರ",
    heroTitle: "ಮೈಸೂರು ದಸರಾ ೨೦೨೫ಗೆ ಸ್ವಾಗತ",
    heroSubtitle: "ನಿಮ್ಮ ಹಬ್ಬದ ಸಂಗಾತಿ - ಕಾರ್ಯಕ್ರಮಗಳು, ಸಾರಿಗೆ ಮತ್ತು ನೆನಪುಗಳನ್ನು ಸುಲಭವಾಗಿ ಅನ್ವೇಷಿಸಿ.",
    ctaEvents: "ಹತ್ತಿರದ ಕಾರ್ಯಕ್ರಮಗಳು",
    ctaGallery: "ಗ್ಯಾಲರಿ ವೀಕ್ಷಿಸಿ",
    eventsTitle: "ದಸರಾ ಕಾರ್ಯಕ್ರಮಗಳ ನಕ್ಷೆ",
    transportTitle: "ಸಾರಿಗೆ ಮಾರ್ಗಗಳು",
    galleryTitle: "ಛಾಯಾಚಿತ್ರ ಗ್ಯಾಲರಿ",
    home: "ಮುಖಪುಟ",
    events: "ಕಾರ್ಯಕ್ರಮಗಳು",
    transport: "ಸಾರಿಗೆ",
    gallery: "ಗ್ಯಾಲರಿ",
    findRoute: "ಮಾರ್ಗ ಹುಡುಕಿ",
    fromEvent: "ಇಲ್ಲಿಂದ",
    toEvent: "ಇಲ್ಲಿಗೆ",
    calculating: "ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತಿದೆ...",
    routeDetails: "ಮಾರ್ಗದ ವಿವರಗಳು",
    footerText: "© ೨೦೨೫ ದಸರಾ ಮಿತ್ರ. ಮೈಸೂರಿನ ಸಂಭ್ರಮವನ್ನು ಆಚರಿಸೋಣ.",
    footerAboutTitle: "ದಸರಾ ಮಿತ್ರ ಬಗ್ಗೆ",
    footerAboutDescription: "ಮೈಸೂರು ದಸರಾದ ಸಮಯದಲ್ಲಿ ಮಾರ್ಗಗಳು, ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ಅಗತ್ಯ ಮಾಹಿತಿಗಾಗಿ ನಿಮ್ಮ ದ್ವಿಭಾಷಾ ಮಾರ್ಗದರ್ಶಿ.",
    footerDiscoverTitle: "ದಸರಾ ಅನ್ವೇಷಿಸಿ",
    footerVisitTitle: "ನಿಮ್ಮ ಪ್ರವಾಸ ಯೋಜಿಸಿ",
    footerConnectTitle: "ಸಂಪರ್ಕಿಸಿ",
    footerAddress: "ಮೈಸೂರು, ಕರ್ನಾಟಕ, ಭಾರತ",
    footerDisclaimer: "ಸಮುದಾಯ ನಿರ್ಮಿತ ಮಾರ್ಗದರ್ಶಿ. ಮೈಸೂರು ದಸರಾ ಆಡಳಿತದಿಂದ ಪರಿಶೀಲಿತ ಮಾಹಿತಿ.",
    footerFestivalDates: "ನವ ರಾತ್ರಿ • ಅಕ್ಟೋಬರ್ ೧ – ೧೦, ೨೦೨೫",
    footerPlanTip: "ಜಂಬೂ ಸವಾರಿ ಭವ್ಯ ಮೆರವಣಿಗೆ ವೀಕ್ಷಿಸಲು ಸಂಜೆ ೪ಕ್ಕೆ ಮುನ್ನ ಸ್ಥಳ ತಲುಪಿ.",
    footerSocialTitle: "ಹಬ್ಬದ ಕ್ಷಣಗಳನ್ನು ಅನುಸರಿಸಿ",
    footerSocialInstagram: "Instagram",
    footerSocialYoutube: "YouTube",
    footerSocialFacebook: "Facebook",
    footerSocialX: "X (Twitter)",
    footerNewsletterTitle: "ಹಬ್ಬದ ಸುದ್ದಿ ಪತ್ರಿಕೆ",
    footerNewsletterDescription: "ಪ್ರತಿ ದಿನದ ಮುಖ್ಯಾಂಶಗಳು, ಮಾರ್ಗ ಬದಲಾವಣೆಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ವಿವರಗಳನ್ನು ನೇರವಾಗಿ ಪಡೆಯಿರಿ.",
    footerNewsletterPlaceholder: "ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    footerNewsletterCta: "ನನ್ನನ್ನು ತಿಳಿಸಿ",
    footerNewsletterDisclaimer: "Spam ಇಲ್ಲ. ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಬೇರ್ಪಡಿಸಬಹುದು. ಹಬ್ಬದ ಅವಧಿಯಲ್ಲಿ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಹಂಚಲಾಗುತ್ತದೆ.",
    nearest: "ನಿಮ್ಮ ಹತ್ತಿರ",
    chatTitle: "ದಸರಾ ಸಹಾಯಕ",
    chatPlaceholder: "ಕಾರ್ಯಕ್ರಮಗಳು, ಮಾರ್ಗಗಳು ಅಥವಾ ಇತಿಹಾಸದ ಬಗ್ಗೆ ಕೇಳಿ...",
    send: "ಕಳುಹಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error: "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
    enableLocation: "ನಿಮ್ಮ ಹತ್ತಿರದ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಹುಡುಕಲು ಸ್ಥಳ ಹಂಚಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ!",
    locationDenied: "ಸ್ಥಳ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಎಲ್ಲಾ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    category: "ವರ್ಗ",
    time: "ಸಮಯ",
    directions: "ಮಾರ್ಗಗಳು",
    distance: "ದೂರ",
    duration: "ಅವಧಿ",
    routeNeedLocation: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಲು ಸ್ಥಳ ಹಂಚಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.",
    routeFetching: "ಉತ್ತಮ ಮಾರ್ಗವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    routeUnavailable: "ಈ ಕ್ಷಣ ಮಾರ್ಗ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    routeReady: "ನಡೆದಾಡಲು ಸೂಕ್ತ ಮಾರ್ಗ ಸಿದ್ಧವಾಗಿದೆ",
    clearRoute: "ಮಾರ್ಗವನ್ನು ಅಳಿಸಿ",
    searchPlaceholder: "ಕಾರ್ಯಕ್ರಮಗಳು ಅಥವಾ ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...",
    clearSearch: "ಅಳಿಸಿ",
    dayFilterLabel: "ದಿನ ಯಾವುದು?",
    allDays: "ಎಲ್ಲಾ ದಿನಗಳು",
    dayLabel: "ದಿನ",
    categoryFilterLabel: "ವರ್ಗ ಆಯ್ಕೆ",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    ageFilterLabel: "ವಯಸ್ಸಿನ ವರ್ಗ",
    allAgeGroups: "ಎಲ್ಲಾ ವಯಸ್ಸಿನ ಗುಂಪುಗಳು",
    statusLabel: "ಸ್ಥಿತಿ",
    statusLive: "ಪ್ರಸ್ತುತ",
    statusUpcoming: "ಬರುತ್ತಿದೆ",
    statusCompleted: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    routeInstructionsTitle: "ಹಂತ ಹಂತದ ಮಾರ್ಗ ಸೂಚನೆ",
    noInstructions: "ಈ ಮಾರ್ಗಕ್ಕೆ ವಿವರವಾದ ಸೂಚನೆಗಳಿಲ್ಲ.",
    routeRestrictionsTitle: "ಮಾರ್ಗ ಸಲಹೆಗಳು",
    noRestrictions: "ಈ ಮಾರ್ಗದಲ್ಲಿ ಯಾವುದೇ ನಿರ್ಬಂಧಗಳಿಲ್ಲ.",
    activeOnDays: "ಸಕ್ರಿಯ ದಿನಗಳು",
    restrictionRadius: "ನಿರ್ಬಂಧಿತ ವ್ಯಾಪ್ತಿ",
    metersUnit: "ಮೀ",
    kilometersUnit: "ಕಿ.ಮೀ",
    secondsUnitShort: "ಸೆ",
    minutesUnitShort: "ನಿ",
    jambooStartLabel: "ಮೈಸೂರು ಅರಮನೆ – ಬಾಲರಾಮ ಬಾಗಿಲು",
    jambooEndLabel: "ಬನ್ನಿಮಂಟಪ ಮೈದಾನ",
    jambooRouteLabel: "ದಸರಾ ಮೆರವಣಿಗೆ ಮಾರ್ಗ",
    showClosures: "ರಸ್ತೆ ಬಂದ್ ಸ್ಥಳಗಳು",
    hideClosures: "ರಸ್ತೆ ಬಂದ್ ಮರೆಮಾಡಿ",
    closuresTitle: "ರಸ್ತೆ ಬಂದ್ ವಿವರಗಳು",
    noEvents: "ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ.",
    noEventsForDay: "ದಿನಕ್ಕೆ ಯಾವುದೇ ಕಾರ್ಯಕ್ರಮವಿಲ್ಲ",
    noSearchResults: "ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದಿಕೆಯಿಲ್ಲ",
    searchHint: "ಬೇರೆ ಹೆಸರು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅಳಿಸಿ ಎಲ್ಲಾ ಸ್ಥಳಗಳನ್ನು ನೋಡಿ.",
    noFilterResults: "ಆಯ್ದ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ."
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return TRANSLATIONS[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'kn' : 'en');
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);