import React, { createContext, useContext, useState } from 'react';

export const EVENTS_DATA = [
  {
    id: 1,
    name: "Jumboo Savari",
    name_kn: "ಜಂಬೂ ಸವಾರಿ",
    name_hi: "जम्बू सवारी",
    lat: 12.3051,
    lng: 76.6551,
    description: "The grand elephant procession marking the finale of Dasara.",
    description_kn: "ದಸರಾ ಹಬ್ಬದ ಅಂತ್ಯವನ್ನು ಗುರುತಿಸುವ ಪ್ರಮುಖ ಆನೆ ಮೆರವಣಿಗೆ.",
    description_hi: "दशहरा समापन का भव्य हाथी जुलूस।",
    time: "Oct 12, 2:30 PM",
    category: "Parade",
    day: 10,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 2,
    name: "Torchlight Parade",
    name_kn: "ಪಂಜಿನ ಕವಾಯತು",
    name_hi: "टॉर्चलाइट परेड",
    lat: 12.3225,
    lng: 76.6589,
    description: "A spectacular display of lights and military drills at Bannimantap.",
    description_kn: "ಬನ್ನಿಮಂಟಪದಲ್ಲಿ ದೀಪಗಳು ಮತ್ತು ಸೇನಾ ಕವಾಯತಿನ ಅದ್ಭುತ ಪ್ರದರ್ಶನ.",
    description_hi: "बन्नीमंतप में रोशनी और सैन्य अभ्यास का शानदार प्रदर्शन।",
    time: "Oct 12, 7:00 PM",
    category: "Parade",
    day: 9,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 3,
    name: "Mysore Palace Illumination",
    name_kn: "ಮೈಸೂರು ಅರಮನೆ ದೀಪಾಲಂಕಾರ",
    name_hi: "मैसूरु पैलेस रोशनी",
    lat: 12.3052,
    lng: 76.6552,
    description: "The palace lit up with nearly 100,000 bulbs.",
    description_kn: "ಸುಮಾರು ೧ ಲಕ್ಷ ದೀಪಗಳಿಂದ ಬೆಳಗುವ ಅರಮನೆ.",
    description_hi: "लगभग एक लाख बल्बों से जगमगाता महल।",
    time: "Daily, 7:00 PM",
    category: "Sightseeing",
    day: 1,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 4,
    name: "Dasara Exhibition",
    name_kn: "ದಸರಾ ವಸ್ತುಪ್ರದರ್ಶನ",
    name_hi: "दशहरा प्रदर्शनी",
    lat: 12.3020,
    lng: 76.6600,
    description: "Shopping, food, and entertainment stalls opposite the palace.",
    description_kn: "ಅರಮನೆಯ ಎದುರು ಶಾಪಿಂಗ್, ಊಟ ಮತ್ತು ಮನರಂಜನೆ ಮಳಿಗೆಗಳು.",
    description_hi: "महल के सामने खरीदारी, भोजन और मनोरंजन स्टॉल।",
    time: "Daily, 10:00 AM - 9:00 PM",
    category: "Fair",
    day: 2,
    status: 'live',
    ageGroup: 'Family',
    ageGroup_kn: 'ಕುಟುಂಬ',
    ageGroup_hi: 'परिवार'
  },
  {
    id: 5,
    name: "Flower Show",
    name_kn: "ಫಲಪುಷ್ಪ ಪ್ರದರ್ಶನ",
    name_hi: "फूल प्रदर्शनी",
    lat: 12.3000,
    lng: 76.6700,
    description: "Exotic floral arrangements at Kuppanna Park.",
    description_kn: "ಕುಪ್ಪಣ್ಣ ಪಾರ್ಕ್‌ನಲ್ಲಿ ವಿಲಕ್ಷಣ ಹೂವಿನ ಅಲಂಕಾರಗಳು.",
    description_hi: "कुप्पन्ना पार्क में विदेशी पुष्प सज्जा।",
    time: "Daily, 9:00 AM - 9:00 PM",
    category: "Nature",
    day: 3,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 6,
    name: "Yuva Dasara",
    name_kn: "ಯುವ ದಸರಾ",
    name_hi: "युवा दशहरा",
    lat: 12.3100,
    lng: 76.6300,
    description: "Concerts and youth cultural programs at Maharaja's College Grounds.",
    description_kn: "ಮಹಾರಾಜ ಕಾಲೇಜು ಮೈದಾನದಲ್ಲಿ ಸಂಗೀತ ಮತ್ತು ಯುವ ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು.",
    description_hi: "महाराजा कॉलेज मैदान में कॉन्सर्ट और युवा सांस्कृतिक कार्यक्रम।",
    time: "Oct 6-10, 6:00 PM",
    category: "Music",
    day: 5,
    status: 'live',
    ageGroup: 'Youth',
    ageGroup_kn: 'ಯುವ',
    ageGroup_hi: 'युवा'
  },
  {
    id: 7,
    name: "Wrestling Tournament",
    name_kn: "ಕುಸ್ತಿ ಪಂದ್ಯಾವಳಿ",
    name_hi: "कुश्ती प्रतियोगिता",
    lat: 12.3080,
    lng: 76.6500,
    description: "Traditional Nada Kusti wrestling matches.",
    description_kn: "ಸಾಂಪ್ರದಾಯಿಕ ನಾಡ ಕುಸ್ತಿ ಪಂದ್ಯಗಳು.",
    description_hi: "परंपरागत नाडा कुश्ती मुकाबले।",
    time: "Oct 5-9, 4:00 PM",
    category: "Sports",
    day: 6,
    status: 'live',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 8,
    name: "Poets' Conference (Kavi Goshti)",
    name_kn: "ಕವಿ ಗೋಷ್ಠಿ",
    name_hi: "कवि गोष्ठी",
    lat: 12.3040,
    lng: 76.6530,
    description: "Gathering of renowned poets and literature lovers.",
    description_kn: "ಪ್ರಖ್ಯಾತ ಕವಿಗಳು ಮತ್ತು ಸಾಹಿತ್ಯ ಪ್ರೇಮಿಗಳ ಸಭೆ.",
    description_hi: "प्रसिद्ध कवियों और साहित्य प्रेमियों का मिलन।",
    time: "Oct 7, 10:00 AM",
    category: "Culture",
    day: 4,
    status: 'completed',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 9,
    name: "Food Mela (Ahaara Mela)",
    name_kn: "ಆಹಾರ ಮೇಳ",
    name_hi: "आहार मेला",
    lat: 12.2990,
    lng: 76.6450,
    description: "Traditional delicacies from across Karnataka.",
    description_kn: "ಕರ್ನಾಟದಾದ್ಯಂತದ ಸಾಂಪ್ರದಾಯಿಕ ಖಾದ್ಯಗಳು.",
    description_hi: "कर्नाटक भर के पारंपरिक व्यंजन।",
    time: "Daily, 11:00 AM - 10:00 PM",
    category: "Food",
    day: 7,
    status: 'live',
    ageGroup: 'Family',
    ageGroup_kn: 'ಕುಟುಂಬ',
    ageGroup_hi: 'परिवार'
  },
  {
    id: 10,
    name: "Cultural Programs at Palace",
    name_kn: "ಅರಮನೆಯಲ್ಲಿ ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳು",
    name_hi: "महल में सांस्कृतिक कार्यक्रम",
    lat: 12.3051,
    lng: 76.6551,
    description: "Classical music and dance performances in front of the illuminated palace.",
    description_kn: "ದೀಪಾಲಂಕೃತ ಅರಮನೆಯ ಮುಂಭಾಗದಲ್ಲಿ ಶಾಸ್ತ್ರೀಯ ಸಂಗೀತ ಮತ್ತು ನೃತ್ಯ ಪ್ರದರ್ಶನಗಳು.",
    description_hi: "जगमगाते महल के सामने शास्त्रीय संगीत और नृत्य प्रस्तुतियाँ।",
    time: "Daily, 6:00 PM",
    category: "Culture",
    day: 8,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 11,
    name: "Drone Light Show",
    name_kn: "ಡ್ರೋನ್ ಬೆಳಕು ಪ್ರದರ್ಶನ",
    name_hi: "ड्रोन लाइट शो",
    lat: 12.295,
    lng: 76.681,
    description: "Synchronized drones create immersive formations above Lalitha Mahal grounds.",
    description_kn: "ಲಲಿತಾ ಮಹಲ್ ಮೈದಾನದ ಮೇಲೆ ಡ್ರೋನ್‌ಗಳು ಅದ್ಭುತ ವಿನ್ಯಾಸಗಳನ್ನು ನಿರ್ಮಿಸುತ್ತವೆ.",
    description_hi: "समन्वित ड्रोन ललिता महल मैदान के ऊपर अद्भुत आकृतियां बनाते हैं।",
    time: "Oct 8-10, 8:30 PM",
    category: "Light Show",
    day: 9,
    status: 'upcoming',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 12,
    name: "Heritage Street Performances",
    name_kn: "ಪಾರಂಪರಿಕ ರಸ್ತೆ ಪ್ರದರ್ಶನಗಳು",
    name_hi: "विरासत सड़क प्रदर्शन",
    lat: 12.3074,
    lng: 76.6529,
    description: "Traditional folk artists take over the illuminated Devaraja Market streets.",
    description_kn: "ಅಲಂಕೃತ ದೇವರಾಜ ಮಾರುಕಟ್ಟೆ ರಸ್ತೆಯಲ್ಲಿ ಪಾರಂಪರಿಕ ಜನಪದ ಕಲಾವಿದರು ಪ್ರದರ್ಶನ ನೀಡುತ್ತಾರೆ.",
    description_hi: "देवराजा मार्केट की जगमगाती गलियों में लोक कलाकार प्रस्तुतियाँ देते हैं।",
    time: "Daily, 6:00 PM - 9:00 PM",
    category: "Culture",
    day: 4,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 13,
    name: "Makkala Dasara",
    name_kn: "ಮಕ್ಕಳ ದಸರಾ",
    name_hi: "मक्कला दशहरा",
    lat: 12.3152,
    lng: 76.6308,
    description: "Interactive workshops, storytelling corners, and science demos for children.",
    description_kn: "ಮಕ್ಕಳಿಗಾಗಿ ಕಾರ್ಯಾಗಾರಗಳು, ಕಥೆ ಹೇಳುವ ಮೂಲೆಗಳು ಮತ್ತು ವಿಜ್ಞಾನ ಪ್ರದರ್ಶನಗಳು.",
    description_hi: "बच्चों के लिए कार्यशालाएँ, कहानी कोने और विज्ञान डेमो।",
    time: "Oct 4-6, 10:00 AM - 5:00 PM",
    category: "Kids",
    day: 3,
    status: 'completed',
    ageGroup: 'Kids',
    ageGroup_kn: 'ಮಕ್ಕಳು',
    ageGroup_hi: 'बच्चे'
  },
  {
    id: 14,
    name: "Raitha Dasara",
    name_kn: "ರೈತ ದಸರಾ",
    name_hi: "रैथा दशहरा",
    lat: 12.3286,
    lng: 76.6548,
    description: "Farmer felicitation, agri-tech demos, and organic produce fair at JSS Grounds.",
    description_kn: "ಜಿಎಸ್‌ಎಸ್ ಮೈದಾನದಲ್ಲಿ ರೈತರ ಸನ್ಮಾನ, ಕೃಷಿ ತಂತ್ರಜ್ಞಾನ ಪ್ರದರ್ಶನ ಮತ್ತು ಸಾವಯವ ಮಾರುಕಟ್ಟೆ.",
    description_hi: "JSS मैदान में किसान सम्मान, एग्री-टेक डेमो और जैविक उत्पाद मेला।",
    time: "Oct 5-7, 9:00 AM - 6:00 PM",
    category: "Agriculture",
    day: 4,
    status: 'completed',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 15,
    name: "Vintage Car Rally",
    name_kn: "ವಿಂಟೇಜ್ ಕಾರು ರ‍್ಯಾಲಿ",
    name_hi: "विंटेज कार रैली",
    lat: 12.3091,
    lng: 76.6577,
    description: "Classic cars parade from the palace to Lalitha Mahal with live commentary.",
    description_kn: "ಅರಮನೆದಿಂದ ಲಲಿತಾ ಮಹಲ್‌ವರೆಗೆ ವಿಂಟೇಜ್ ಕಾರುಗಳ ಮೆರವಣಿಗೆ ಮತ್ತು ಸಜೀವ ವಿವರಣೆ.",
    description_hi: "महल से ललिता महल तक विंटेज कारों की परेड लाइव कॉमेंट्री के साथ।",
    time: "Oct 6, 7:30 AM",
    category: "Lifestyle",
    day: 5,
    status: 'completed',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 16,
    name: "Yoga by the Palace",
    name_kn: "ಅರಮನೆ ಬಳಿ ಯೋಗ",
    name_hi: "महल के पास योग",
    lat: 12.3046,
    lng: 76.6555,
    description: "Sunrise yoga sessions led by renowned instructors with palace backdrop.",
    description_kn: "ಪರಿಚಿತ ಶಿಕ್ಷಕರಿಂದ ಅರಮನೆ ಹಿನ್ನೆಲೆಯೊಂದಿಗೆ ಸೂರ್ಯೋದಯ ಯೋಗ ಶಿಬಿರ.",
    description_hi: "प्रसिद्ध प्रशिक्षकों के साथ महल की पृष्ठभूमि में सूर्योदय योग सत्र।",
    time: "Oct 3-9, 6:00 AM",
    category: "Wellness",
    day: 2,
    status: 'live',
    ageGroup: 'Adults',
    ageGroup_kn: 'ವಯಸ್ಕರು',
    ageGroup_hi: 'वयस्क'
  },
  {
    id: 17,
    name: "Folk Dance Utsav",
    name_kn: "ಜನಪದ ನೃತ್ಯ ಉತ್ಸವ",
    name_hi: "लोक नृत्य उत्सव",
    lat: 12.3121,
    lng: 76.6469,
    description: "Teams from across Karnataka perform vibrant folk dances at Town Hall.",
    description_kn: "ಕರ್ನಾಟಕದ ವಿವಿಧ ತಂಡಗಳು ಟೌನ್ ಹಾಲ್‌ನಲ್ಲಿ ಚೆಲುವಾದ ಜನಪದ ನೃತ್ಯ ಪ್ರದರ್ಶನ ನೀಡುತ್ತವೆ.",
    description_hi: "कर्नाटक भर की टीमें टाउन हॉल में रंगीन लोक नृत्य प्रस्तुत करती हैं।",
    time: "Oct 7-9, 5:00 PM - 8:00 PM",
    category: "Dance",
    day: 6,
    status: 'live',
    ageGroup: 'All Ages',
    ageGroup_kn: 'ಎಲ್ಲಾ ವಯಸ್ಸು',
    ageGroup_hi: 'सभी आयु'
  },
  {
    id: 18,
    name: "Adventure Sports Zone",
    name_kn: "ಸಾಹಸ ಕ್ರೀಡೆ ವಲಯ",
    name_hi: "एडवेंचर स्पोर्ट्स ज़ोन",
    lat: 12.2995,
    lng: 76.6672,
    description: "Ziplining, wall climbing, and obstacle courses at Chamundi Vihar Stadium.",
    description_kn: "ಚಾಮುಂಡಿ ವಿಹಾರ ಕ್ರೀಡಾಂಗಣದಲ್ಲಿ ಜಿಪ್‌ಲೈನ್, ಗೋಡೆ ಏರಿಕೆ ಮತ್ತು ಅಡೆತಡೆ ಆಟಗಳು.",
    description_hi: "चामुंडी विहार स्टेडियम में ज़िपलाइन, वॉल क्लाइम्ब और बाधा पाठ्यक्रम।",
    time: "Oct 5-10, 10:00 AM - 7:00 PM",
    category: "Adventure",
    day: 7,
    status: 'live',
    ageGroup: 'Youth',
    ageGroup_kn: 'ಯುವ',
    ageGroup_hi: 'युवा'
  }
];

export const ROAD_CLOSURES = [
  {
    id: 'closure-palace-road',
    name: 'Palace Road Barricade',
    name_kn: 'ಅರಮನೆ ರಸ್ತೆ ಅಡ್ಡಿ',
    lat: 12.3058,
    lng: 76.6558,
    description: 'Access closed for parade rehearsal from 1 PM - 8 PM.',
    description_kn: 'ಮೆರವಣಿಗೆ ಅಭ್ಯಾಸದ ಕಾರಣ ಮಧ್ಯಾಹ್ನ ೧ ರಿಂದ ರಾತ್ರಿ ೮ರವರೆಗೆ ಪ್ರವೇಶ ಮುಚ್ಚಲಾಗಿದೆ.',
    days: [9, 10],
    radius: 220
  },
  {
    id: 'closure-bannimantap',
    name: 'Bannimantap Grounds Diversion',
    name_kn: 'ಬನ್ನಿಮಂಟಪ ದಾರಿದೀಪ ಬದಲಾವಣೆ',
    lat: 12.3185,
    lng: 76.6572,
    description: 'Night traffic diverted for torchlight rehearsal 6 PM - 10 PM.',
    description_kn: 'ಟಾರ್ಚ್‌ಲೈಟ್ ಅಭ್ಯಾಸಕ್ಕಾಗಿ ರಾತ್ರಿ ೬ ರಿಂದ ೧೦ರವರೆಗೆ ವಾಹನ ಸಂಚಾರ ಮತ್ತೊಂದು ಮಾರ್ಗಕ್ಕೆ ಪರಿವರ್ತನೆ.',
    days: [8, 9, 10],
    radius: 180
  },
  {
    id: 'closure-doddakere',
    name: 'Doddakere Maidan Parking Restriction',
    name_kn: 'ದೊಡ್ಡಕೆರೆ ಮೈದಾನ ವಾಹನ ನಿಲುಗಡೆ ನಿರ್ಬಂಧ',
    lat: 12.3036,
    lng: 76.6579,
    description: 'Only shuttle buses allowed between 9 AM - 11 PM.',
    description_kn: 'ಬೆಳಿಗ್ಗೆ ೯ರಿಂದ ರಾತ್ರಿ ೧೧ರವರೆಗೆ ಶಟಲ್ ಬಸ್ಸುಗಳಿಗೆ ಮಾತ್ರ ಅನುಮತಿ.',
    days: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    radius: 160
  },
  {
    id: 'closure-jamboo-route',
    name: 'Jamboo Savari Procession Route',
    name_kn: 'ಜಂಬೂ ಸವಾರಿ ಮೆರವಣಿಗೆ ಮಾರ್ಗ',
    lat: 12.3198,
    lng: 76.6607,
    description: 'Entire 5 km corridor from Mysuru Palace (Balarama Gate) to Bannimantap Grounds closed for vehicles from 8 AM - 8 PM on the grand finale day.',
    description_kn: 'ಅಂತಿಮ ದಿನ ಬೆಳಿಗ್ಗೆ ೮ ರಿಂದ ರಾತ್ರಿ ೮ರವರೆಗೆ ಮೈಸೂರು ಅರಮನೆ (ಬಾಲರಾಮ ದಿಂದ)ದಿಂದ ಬನ್ನಿಮಂಟಪ ಮೈದಾನವರೆಗೆ ೫ ಕಿಮೀ ಮಾರ್ಗವು ಎಲ್ಲಾ ವಾಹನಗಳಿಗೆ ಸಂಪೂರ್ಣವಾಗಿ ಮುಚ್ಚಲ್ಪಟ್ಟಿದೆ.',
    days: [10],
    radius: 120,
    pathBuffer: 250,
    path: [
      { lat: 12.305163, lng: 76.6551749 },
      { lat: 12.30568, lng: 76.65594 },
      { lat: 12.30664, lng: 76.6569 },
      { lat: 12.30775, lng: 76.65793 },
      { lat: 12.30894, lng: 76.65848 },
      { lat: 12.31012, lng: 76.65841 },
      { lat: 12.31193, lng: 76.65766 },
      { lat: 12.31375, lng: 76.65705 },
      { lat: 12.31568, lng: 76.65647 },
      { lat: 12.31752, lng: 76.65602 },
      { lat: 12.31913, lng: 76.65566 },
      { lat: 12.32074, lng: 76.65545 },
      { lat: 12.32247, lng: 76.65531 },
      { lat: 12.32428, lng: 76.6552 },
      { lat: 12.32606, lng: 76.65512 },
      { lat: 12.32782, lng: 76.65504 },
      { lat: 12.32959, lng: 76.655 },
      { lat: 12.33147, lng: 76.65499 },
      { lat: 12.33328, lng: 76.65499 },
      { lat: 12.3340167, lng: 76.6549883 }
    ]
  }
];

export const TRANSLATIONS = {
  en: {
    title: "Dasara Mitra",
    heroTitle: "Welcome to Mysore Dasara 2025",
    heroSubtitle: "Your Festival Companion – Navigate events, transport, and memories effortlessly.",
    ctaEvents: "Find Nearest Events",
    ctaGallery: "Explore Gallery",
    eventsTitle: "Festival Events Map",
    transportTitle: "Transport Route Planner",
    galleryTitle: "Photo Gallery",
    home: "Home",
    events: "Events",
    transport: "Transport",
    gallery: "Gallery",
    findRoute: "Find Route",
    fromEvent: "From Event",
    toEvent: "To Event",
    calculating: "Calculating...",
    routeDetails: "Route Details",
    footerText: "© 2025 Dasara Mitra. Celebrating the spirit of Mysore.",
    footerAboutTitle: "About Dasara Mitra",
    footerAboutDescription: "Your bilingual festival navigator for routes, events, and on-ground essentials during Mysuru Dasara.",
    footerDiscoverTitle: "Discover Dasara",
    footerVisitTitle: "Plan your visit",
    footerContactTitle: "Festival helpdesk",
    footerContactPhoneLabel: "Helpline",
    footerContactPhoneValue: "+91 78931XXXXX",
    footerContactEmailLabel: "Email",
    footerContactEmailValue: "support@dasaramitra.in",
    footerContactHoursLabel: "Timings",
    footerContactHoursValue: "Daily 9 AM – 10 PM IST",
    footerContactOfficeLabel: "Command center",
    footerContactOfficeValue: "Dasara Exhibition Grounds, Mysuru",
    footerConnectTitle: "Stay in touch",
    footerAddress: "Mysuru, Karnataka, India",
    footerDisclaimer: "Community-built companion. Information verified with Mysuru Dasara authorities.",
    footerFestivalDates: "Navaratri • 1 – 10 Oct 2025",
    footerPlanTip: "Arrive by 4 PM to secure vantage points for the grand Jamboo Savari procession.",
    footerDailyFlowTitle: "Daily Festival Flow",
    footerDailyFlowDescription: "Stay ahead of the day-wise highlights and never miss a spectacle.",
    footerSocialTitle: "Follow the celebrations",
    footerSocialInstagram: "Instagram",
    footerSocialYoutube: "YouTube",
    footerSocialFacebook: "Facebook",
    footerSocialX: "X (Twitter)",
    footerNewsletterTitle: "Festival bulletin",
    footerNewsletterDescription: "Get daily highlights, road updates, and exclusive cultural insights in your inbox.",
    footerNewsletterPlaceholder: "Enter your email",
    footerNewsletterCta: "Keep me updated",
    footerNewsletterDisclaimer: "No spam. Unsubscribe anytime. Updates shared during festival week.",
    nearest: "Nearest to you",
    chatTitle: "Dasara Helper",
    chatPlaceholder: "Ask about events, routes, or history...",
    send: "Send",
    loading: "Loading...",
    error: "Something went wrong.",
    enableLocation: "Enable location to find events near you!",
    locationDenied: "Location access denied. Showing all events.",
    category: "Category",
    time: "Time",
    directions: "Get Directions",
    distance: "Distance",
    duration: "Duration",
    routeNeedLocation: "Enable location to get directions.",
    routeFetching: "Fetching the best route...",
    routeUnavailable: "Route unavailable right now. Please try again in a moment.",
    routeReady: "Walking route ready",
    clearRoute: "Clear Route",
    searchPlaceholder: "Search events or categories...",
    clearSearch: "Clear",
    dayFilterLabel: "Filter by day",
    allDays: "All days",
    dayLabel: "Day",
    categoryFilterLabel: "Filter by category",
    allCategories: "All categories",
    ageFilterLabel: "Age category",
    allAgeGroups: "All age groups",
    statusLabel: "Status",
    statusLive: "Live",
    statusUpcoming: "Upcoming",
    statusCompleted: "Completed",
    routeInstructionsTitle: "Turn-by-turn directions",
    noInstructions: "Detailed steps are unavailable for this route.",
    routeRestrictionsTitle: "Route advisories",
    noRestrictions: "No restrictions along this route.",
    activeOnDays: "Active on days",
    restrictionRadius: "Restricted radius",
    metersUnit: "m",
    kilometersUnit: "km",
    secondsUnitShort: "sec",
    minutesUnitShort: "min",
    jambooStartLabel: "Mysuru Palace – Balarama Gate",
    jambooEndLabel: "Bannimantap Grounds",
    jambooRouteLabel: "Grand Procession Corridor",
    showClosures: "Show road blockages",
    hideClosures: "Hide road blockages",
    closuresTitle: "Road blockages",
    noEvents: "No events available.",
    noEventsForDay: "No events scheduled for Day",
    noSearchResults: "No matches for",
    searchHint: "Try a different event name or clear the filters to explore everything.",
    noFilterResults: "No events match the selected filters."
  },
  kn: {
    title: "ದಸರಾ ಮಿತ್ರ",
    heroTitle: "ಮೈಸೂರು ದಸರಾ ೨೦೨೫ಗೆ ಸ್ವಾಗತ",
    heroSubtitle: "ನಿಮ್ಮ ಹಬ್ಬದ ಸಂಗಾತಿ - ಕಾರ್ಯಕ್ರಮಗಳು, ಸಾರಿಗೆ ಮತ್ತು ನೆನಪುಗಳನ್ನು ಸುಲಭವಾಗಿ ಅನ್ವೇಷಿಸಿ.",
    ctaEvents: "ಹತ್ತಿರದ ಕಾರ್ಯಕ್ರಮಗಳು",
    ctaGallery: "ಗ್ಯಾಲರಿ ವೀಕ್ಷಿಸಿ",
    eventsTitle: "ದಸರಾ ಕಾರ್ಯಕ್ರಮಗಳ ನಕ್ಷೆ",
    transportTitle: "ಸಾರಿಗೆ ಮಾರ್ಗಗಳು",
    galleryTitle: "ಛಾಯಾಚಿತ್ರ ಗ್ಯಾಲರಿ",
    home: "ಮುಖಪುಟ",
    events: "ಕಾರ್ಯಕ್ರಮಗಳು",
    transport: "ಸಾರಿಗೆ",
    gallery: "ಗ್ಯಾಲರಿ",
    findRoute: "ಮಾರ್ಗ ಹುಡುಕಿ",
    fromEvent: "ಇಲ್ಲಿಂದ",
    toEvent: "ಇಲ್ಲಿಗೆ",
    calculating: "ಲೆಕ್ಕಹಾಕಲಾಗುತ್ತಿದೆ...",
    routeDetails: "ಮಾರ್ಗದ ವಿವರಗಳು",
    footerText: "© ೨೦೨೫ ದಸರಾ ಮಿತ್ರ. ಮೈಸೂರಿನ ಸಂಭ್ರಮವನ್ನು ಆಚರಿಸೋಣ.",
    footerAboutTitle: "ದಸರಾ ಮಿತ್ರ ಬಗ್ಗೆ",
    footerAboutDescription: "ಮೈಸೂರು ದಸರಾದ ಸಮಯದಲ್ಲಿ ಮಾರ್ಗಗಳು, ಕಾರ್ಯಕ್ರಮಗಳು ಮತ್ತು ಅಗತ್ಯ ಮಾಹಿತಿಗಾಗಿ ನಿಮ್ಮ ದ್ವಿಭಾಷಾ ಮಾರ್ಗದರ್ಶಿ.",
    footerDiscoverTitle: "ದಸರಾ ಅನ್ವೇಷಿಸಿ",
    footerVisitTitle: "ನಿಮ್ಮ ಪ್ರವಾಸ ಯೋಜಿಸಿ",
    footerContactTitle: "ಹಬ್ಬದ ಸಹಾಯ ಕೇಂದ್ರ",
    footerContactPhoneLabel: "ಸಹಾಯವಾಣಿ",
    footerContactPhoneValue: "+91 78931XXXXX",
    footerContactEmailLabel: "ಇಮೇಲ್",
    footerContactEmailValue: "support@dasaramitra.in",
    footerContactHoursLabel: "ಸೇವಾ ಸಮಯ",
    footerContactHoursValue: "ಪ್ರತಿದಿನ ಬೆಳಿಗ್ಗೆ ೯ – ರಾತ್ರಿ ೧೦ (IST)",
    footerContactOfficeLabel: "ನಿಯಂತ್ರಣ ಕೇಂದ್ರ",
    footerContactOfficeValue: "ದಸರಾ ಪ್ರದರ್ಶನ ಮೈದಾನ, ಮೈಸೂರು",
    footerConnectTitle: "ಸಂಪರ್ಕಿಸಿ",
    footerAddress: "ಮೈಸೂರು, ಕರ್ನಾಟಕ, ಭಾರತ",
    footerDisclaimer: "ಸಮುದಾಯ ನಿರ್ಮಿತ ಮಾರ್ಗದರ್ಶಿ. ಮೈಸೂರು ದಸರಾ ಆಡಳಿತದಿಂದ ಪರಿಶೀಲಿತ ಮಾಹಿತಿ.",
    footerFestivalDates: "ನವ ರಾತ್ರಿ • ಅಕ್ಟೋಬರ್ ೧ – ೧೦, ೨೦೨೫",
    footerPlanTip: "ಜಂಬೂ ಸವಾರಿ ಭವ್ಯ ಮೆರವಣಿಗೆ ವೀಕ್ಷಿಸಲು ಸಂಜೆ ೪ಕ್ಕೆ ಮುನ್ನ ಸ್ಥಳ ತಲುಪಿ.",
    footerDailyFlowTitle: "ದಿನವಾರ ಹಬ್ಬದ ಹೊಳೆ",
    footerDailyFlowDescription: "ಪ್ರತಿ ದಿನದ ಸಂಭವಗಳನ್ನು ತಿಳಿದು ವಿಶೇಷ ಕ್ಷಣಗಳನ್ನು ತಪ್ಪಿಸಿಕೊಳ್ಳಬೇಡಿ.",
    footerSocialTitle: "ಹಬ್ಬದ ಕ್ಷಣಗಳನ್ನು ಅನುಸರಿಸಿ",
    footerSocialInstagram: "Instagram",
    footerSocialYoutube: "YouTube",
    footerSocialFacebook: "Facebook",
    footerSocialX: "X (Twitter)",
    footerNewsletterTitle: "ಹಬ್ಬದ ಸುದ್ದಿ ಪತ್ರಿಕೆ",
    footerNewsletterDescription: "ಪ್ರತಿ ದಿನದ ಮುಖ್ಯಾಂಶಗಳು, ಮಾರ್ಗ ಬದಲಾವಣೆಗಳು ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ವಿವರಗಳನ್ನು ನೇರವಾಗಿ ಪಡೆಯಿರಿ.",
    footerNewsletterPlaceholder: "ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ",
    footerNewsletterCta: "ನನ್ನನ್ನು ತಿಳಿಸಿ",
    footerNewsletterDisclaimer: "Spam ಇಲ್ಲ. ಯಾವುದೇ ಸಮಯದಲ್ಲಿ ಬೇರ್ಪಡಿಸಬಹುದು. ಹಬ್ಬದ ಅವಧಿಯಲ್ಲಿ ಅಪ್‌ಡೇಟ್‌ಗಳನ್ನು ಹಂಚಲಾಗುತ್ತದೆ.",
    nearest: "ನಿಮ್ಮ ಹತ್ತಿರ",
    chatTitle: "ದಸರಾ ಸಹಾಯಕ",
    chatPlaceholder: "ಕಾರ್ಯಕ್ರಮಗಳು, ಮಾರ್ಗಗಳು ಅಥವಾ ಇತಿಹಾಸದ ಬಗ್ಗೆ ಕೇಳಿ...",
    send: "ಕಳುಹಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    error: "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
    enableLocation: "ನಿಮ್ಮ ಹತ್ತಿರದ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಹುಡುಕಲು ಸ್ಥಳ ಹಂಚಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ!",
    locationDenied: "ಸ್ಥಳ ಪ್ರವೇಶ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಎಲ್ಲಾ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.",
    category: "ವರ್ಗ",
    time: "ಸಮಯ",
    directions: "ಮಾರ್ಗಗಳು",
    distance: "ದೂರ",
    duration: "ಅವಧಿ",
    routeNeedLocation: "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಲು ಸ್ಥಳ ಹಂಚಿಕೆಯನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.",
    routeFetching: "ಉತ್ತಮ ಮಾರ್ಗವನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    routeUnavailable: "ಈ ಕ್ಷಣ ಮಾರ್ಗ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.",
    routeReady: "ನಡೆದಾಡಲು ಸೂಕ್ತ ಮಾರ್ಗ ಸಿದ್ಧವಾಗಿದೆ",
    clearRoute: "ಮಾರ್ಗವನ್ನು ಅಳಿಸಿ",
    searchPlaceholder: "ಕಾರ್ಯಕ್ರಮಗಳು ಅಥವಾ ವರ್ಗಗಳನ್ನು ಹುಡುಕಿ...",
    clearSearch: "ಅಳಿಸಿ",
    dayFilterLabel: "ದಿನ ಯಾವುದು?",
    allDays: "ಎಲ್ಲಾ ದಿನಗಳು",
    dayLabel: "ದಿನ",
    categoryFilterLabel: "ವರ್ಗ ಆಯ್ಕೆ",
    allCategories: "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    ageFilterLabel: "ವಯಸ್ಸಿನ ವರ್ಗ",
    allAgeGroups: "ಎಲ್ಲಾ ವಯಸ್ಸಿನ ಗುಂಪುಗಳು",
    statusLabel: "ಸ್ಥಿತಿ",
    statusLive: "ಪ್ರಸ್ತುತ",
    statusUpcoming: "ಬರುತ್ತಿದೆ",
    statusCompleted: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    routeInstructionsTitle: "ಹಂತ ಹಂತದ ಮಾರ್ಗ ಸೂಚನೆ",
    noInstructions: "ಈ ಮಾರ್ಗಕ್ಕೆ ವಿವರವಾದ ಸೂಚನೆಗಳಿಲ್ಲ.",
    routeRestrictionsTitle: "ಮಾರ್ಗ ಸಲಹೆಗಳು",
    noRestrictions: "ಈ ಮಾರ್ಗದಲ್ಲಿ ಯಾವುದೇ ನಿರ್ಬಂಧಗಳಿಲ್ಲ.",
    activeOnDays: "ಸಕ್ರಿಯ ದಿನಗಳು",
    restrictionRadius: "ನಿರ್ಬಂಧಿತ ವ್ಯಾಪ್ತಿ",
    metersUnit: "ಮೀ",
    kilometersUnit: "ಕಿ.ಮೀ",
    secondsUnitShort: "ಸೆ",
    minutesUnitShort: "ನಿ",
    jambooStartLabel: "ಮೈಸೂರು ಅರಮನೆ – ಬಾಲರಾಮ ಬಾಗಿಲು",
    jambooEndLabel: "ಬನ್ನಿಮಂಟಪ ಮೈದಾನ",
    jambooRouteLabel: "ದಸರಾ ಮೆರವಣಿಗೆ ಮಾರ್ಗ",
    showClosures: "ರಸ್ತೆ ಬಂದ್ ಸ್ಥಳಗಳು",
    hideClosures: "ರಸ್ತೆ ಬಂದ್ ಮರೆಮಾಡಿ",
    closuresTitle: "ರಸ್ತೆ ಬಂದ್ ವಿವರಗಳು",
    noEvents: "ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ.",
    noEventsForDay: "ದಿನಕ್ಕೆ ಯಾವುದೇ ಕಾರ್ಯಕ್ರಮವಿಲ್ಲ",
    noSearchResults: "ಹುಡುಕಾಟಕ್ಕೆ ಹೊಂದಿಕೆಯಿಲ್ಲ",
    searchHint: "ಬೇರೆ ಹೆಸರು ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅಳಿಸಿ ಎಲ್ಲಾ ಸ್ಥಳಗಳನ್ನು ನೋಡಿ.",
    noFilterResults: "ಆಯ್ದ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಕಾರ್ಯಕ್ರಮಗಳಿಲ್ಲ."
  },
  hi: {
    title: "दसरा मित्र",
    heroTitle: "मैसूरु दशहरा 2025 में आपका स्वागत है",
    heroSubtitle: "आपका उत्सव साथी – कार्यक्रम, यात्रा और यादों को सहज बनाएं।",
    ctaEvents: "पास के कार्यक्रम",
    ctaGallery: "गैलरी देखें",
    eventsTitle: "उत्सव कार्यक्रम मानचित्र",
    transportTitle: "यातायात मार्ग योजनाकार",
    galleryTitle: "फोटो गैलरी",
    home: "मुखपृष्ठ",
    events: "कार्यक्रम",
    transport: "यातायात",
    gallery: "गैलरी",
    findRoute: "मार्ग खोजें",
    fromEvent: "यहाँ से",
    toEvent: "यहाँ तक",
    calculating: "गणना जारी...",
    routeDetails: "मार्ग विवरण",
    footerText: "© 2025 दसरा मित्र। मैसूर की परंपरा का उत्सव।",
    footerAboutTitle: "दसरा मित्र के बारे में",
    footerAboutDescription: "मैसूर दशहरा के दौरान मार्गों, कार्यक्रमों और ज़रूरी जानकारी के लिए आपका द्विभाषी मार्गदर्शक।",
    footerDiscoverTitle: "दशहरा खोजें",
    footerVisitTitle: "अपनी यात्रा योजना",
    footerContactTitle: "उत्सव हेल्पडेस्क",
    footerContactPhoneLabel: "हेल्पलाइन",
    footerContactPhoneValue: "+91 78931XXXXX",
    footerContactEmailLabel: "ईमेल",
    footerContactEmailValue: "support@dasaramitra.in",
    footerContactHoursLabel: "समय",
    footerContactHoursValue: "प्रतिदिन सुबह 9 – रात 10 (IST)",
    footerContactOfficeLabel: "कमांड केंद्र",
    footerContactOfficeValue: "दशहरा प्रदर्शनी मैदान, मैसूरु",
    footerConnectTitle: "संपर्क में रहें",
    footerAddress: "मैसूरु, कर्नाटक, भारत",
    footerDisclaimer: "समुदाय द्वारा बनाया गया साथी। जानकारी मैसूरु दशहरा प्राधिकरण से सत्यापित है।",
    footerFestivalDates: "नवरात्रि • 1 – 10 अक्तूबर 2025",
    footerPlanTip: "भव्य जम्बू सवारी में अच्छा दृश्य पाने के लिए शाम 4 बजे तक पहुँचें।",
    footerDailyFlowTitle: "दैनिक उत्सव क्रम",
    footerDailyFlowDescription: "हर दिन की मुख्य झलक जानें और कोई विशेष क्षण न चूकें।",
    footerSocialTitle: "उत्सव को फ़ॉलो करें",
    footerSocialInstagram: "इंस्टाग्राम",
    footerSocialYoutube: "यूट्यूब",
    footerSocialFacebook: "फेसबुक",
    footerSocialX: "एक्स (ट्विटर)",
    footerNewsletterTitle: "उत्सव समाचारपत्र",
    footerNewsletterDescription: "हर दिन की मुख्य बातें, मार्ग अपडेट और सांस्कृतिक झलक सीधे अपने इनबॉक्स में पाएं।",
    footerNewsletterPlaceholder: "अपना ईमेल दर्ज करें",
    footerNewsletterCta: "मुझे अपडेट करें",
    footerNewsletterDisclaimer: "कोई स्पैम नहीं। कभी भी सदस्यता समाप्त करें। अपडेट केवल उत्सव सप्ताह में भेजे जाएँगे।",
    nearest: "आपके पास",
    chatTitle: "दसरा सहायक",
    chatPlaceholder: "कार्यक्रम, मार्ग या इतिहास पूछें...",
    send: "भेजें",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया।",
    enableLocation: "पास के कार्यक्रम खोजने के लिए स्थान सक्षम करें!",
    locationDenied: "स्थान पहुंच अस्वीकृत। सभी कार्यक्रम दिखाए जा रहे हैं।",
    category: "श्रेणी",
    time: "समय",
    directions: "दिशाएँ",
    distance: "दूरी",
    duration: "अवधि",
    routeNeedLocation: "दिशाएँ पाने के लिए स्थान सक्षम करें।",
    routeFetching: "सबसे अच्छा मार्ग खोजा जा रहा है...",
    routeUnavailable: "अभी मार्ग उपलब्ध नहीं है। कृपया कुछ देर बाद प्रयास करें।",
    routeReady: "पैदल मार्ग तैयार",
    clearRoute: "मार्ग हटाएँ",
    searchPlaceholder: "कार्यक्रम या श्रेणी खोजें...",
    clearSearch: "साफ करें",
    dayFilterLabel: "दिन से फ़िल्टर करें",
    allDays: "सभी दिन",
    dayLabel: "दिन",
    categoryFilterLabel: "श्रेणी द्वारा फ़िल्टर",
    allCategories: "सभी श्रेणियाँ",
    ageFilterLabel: "आयु वर्ग",
    allAgeGroups: "सभी आयु समूह",
    statusLabel: "स्थिति",
    statusLive: "चल रहा है",
    statusUpcoming: "आने वाला",
    statusCompleted: "समाप्त",
    routeInstructionsTitle: "चरण-दर-चरण निर्देश",
    noInstructions: "इस मार्ग के लिए विस्तृत निर्देश उपलब्ध नहीं हैं।",
    routeRestrictionsTitle: "मार्ग सलाह",
    noRestrictions: "इस मार्ग पर कोई प्रतिबंध नहीं।",
    activeOnDays: "सक्रिय दिन",
    restrictionRadius: "प्रतिबंधित त्रिज्या",
    metersUnit: "मीटर",
    kilometersUnit: "किमी",
    secondsUnitShort: "से",
    minutesUnitShort: "मि",
    jambooStartLabel: "मैसूरु पैलेस – बालारामा गेट",
    jambooEndLabel: "बन्नीमंतप मैदान",
    jambooRouteLabel: "भव्य जम्बू सवारी मार्ग",
    showClosures: "सड़क अवरोध दिखाएँ",
    hideClosures: "सड़क अवरोध छिपाएँ",
    closuresTitle: "सड़क अवरोध",
    noEvents: "कोई कार्यक्रम उपलब्ध नहीं।",
    noEventsForDay: "इस दिन के लिए कोई कार्यक्रम नहीं",
    noSearchResults: "का कोई परिणाम नहीं",
    searchHint: "दूसरा नाम आज़माएँ या सभी कार्यक्रम देखने के लिए फ़िल्टर हटाएँ।",
    noFilterResults: "चयनित फ़िल्टर से कोई कार्यक्रम मेल नहीं खाता।"
  }
};

const SUPPORTED_LANGUAGES = ['en', 'kn', 'hi'];
const LANGUAGE_LABELS = {
  en: 'EN',
  kn: 'ಕನ್ನಡ',
  hi: 'हिं'
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(SUPPORTED_LANGUAGES[0]);

  const t = (key) => {
    return TRANSLATIONS[language][key] || key;
  };

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const currentIndex = SUPPORTED_LANGUAGES.indexOf(prev);
      const nextIndex = (currentIndex + 1) % SUPPORTED_LANGUAGES.length;
      return SUPPORTED_LANGUAGES[nextIndex];
    });
  };

  return (
    <LanguageContext.Provider
      value={{
        language,
        toggleLanguage,
        t,
        languageLabel: LANGUAGE_LABELS[language],
        supportedLanguages: SUPPORTED_LANGUAGES
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);